from __future__ import annotations, unicode_literals
import spacy
# tagCaseList = (
#     "PRELAT",  # [der Mann ,] dessen [Hund]
#     "APPRART",  # Small Talk im Beruf
#     "ADJA",
#     "PRELAT",
#     "ADJD",  # Rund eine halbe
#     "PWAV",
#     "NE",  # Vollst andige Namen von Institutionen
#     "PRF",
#     "PIS",  # keiner, viele, man, niemand
#     "PRELS",
#     "PIAT",
#     "APPR",
#     "PWS",
#     "CARD",
#     "PPER",
#     "KON",
#     "KOUI",
#     "PIAT",
#     "PDS",  # dieser, jener
#     "KON",
#     "ART",
#     "NN",
#     "PIS",
#     "PDAT",
#     "ART",
#     "DET",
#     "APPR",
#     "PPOSAT",
# )

# conjunctions = ("aber", "denn", "doch", "oder", "sondern", "und")

# subjunctions = (
#         "als",
#         "bevor",
#         "bis",
#         "da",
#         "damit",
#         "dass",
#         "ehe",
#         "falls",
#         "indem",
#         "nachdem",
#         "obwohl",
#         "seit",
#         "seitdem",
#         "sodass",
#         "solange",
#         "sooft",
#         "während",
#         "weil",
#         "wenn",
#         "wohingegen",
#     )

# datPrepositions = (
#         "aus",
#         "außer",
#         "bei",
#         "mit",
#         "nach",
#         "seit",
#         "von",
#         "zu",
#         "gegenüber" 
#     )

# akkPrepositions = ("für", "um", "durch", "gegen", "bis", "ohne", "wider")

# genPrepositions = (
#         "während",
#         "trotz",
#         "statt",
#         "anstatt",
#         "wegen",
#         "innerhalb",
#         "außerhalb",
#     )

verben_mit_direktem_kasus = {
    "abraten": "DAT, von + DAT",
    "ähneln": "DAT",
    "angehören": "DAT",
    "antworten": "DAT",
    "auffallen": "DAT",
    "ausweichen": "DAT",
    "befehlen": "DAT",
    "begegnen": "DAT",
    "beistehen": "DAT",
    "beitreten": "DAT",
    "danken": "DAT",
    "dienen": "DAT",
    "drohen": "DAT",
    "einfallen": "DAT",
    "entgegnen": "DAT",
    "entsprechen": "DAT",
    "fehlen": "DAT",
    "folgen": "DAT",
    "gefallen": "DAT",
    "gehorchen": "DAT",
    "gehören": "DAT",
    "gelingen": "DAT",
    "genügen": "DAT",
    "glauben": "DAT",
    "glücken": "DAT",
    "missglücken": "DAT",
    "gratulieren": "DAT",
    "helfen": "DAT",
    "missfallen": "DAT",
    "misslingen": "DAT",
    "misstrauen": "DAT",
    "nachgeben": "DAT",
    "nachgehen": "DAT",
    "nähern (sich)": "DAT",
    "nützen": "DAT",
    "passen": "DAT",
    "passieren": "DAT",
    "raten": "DAT, Inf. mit zu",
    "schaden": "DAT",
    "schmecken": "DAT",
    "unterliegen": "DAT (oft)",
    "vertrauen": "DAT",
    "verzeihen": "DAT, AKK (oft)",
    "widersprechen": "DAT",
    "zuhören": "DAT",
    "zulächeln": "DAT",
    "zuraten": "DAT",
    "zureden": "DAT",
    "zusehen": "DAT, bei + DAT",
    "zustimmen": "DAT",
    "zuvorkommen": "DAT" 
}

verbs_with_prepositional_case = {
    "fehlen": "an + DAT",
    "fliehen": "vor + DAT",
    "fordern": "von + DAT",
    "fragen": "nach + DAT",
    "freuen": "über + AKK, auf + AKK",
    "fügen": "in + AKK",
    "führen": "zu + DAT",
    "fürchten": "vor + DAT",
    "gehen": "um + AKK",
    "gehören": "zu + DAT",
    "gelten": "als + NOM",
    "geraten": "in + AKK",
    "gewöhnen": "an + AKK",
    "glauben": "an + AKK",
    "gliedern": "in + AKK",
    "gratulieren": "zu + DAT",
    "halten": "von + DAT",
    "handeln": "von + DAT",
    "handeln": "um + AKK",
    "hoffen": "auf + AKK",
    "hören": "von + DAT",
    "informieren": "über + AKK",
    "interessieren": "für + AKK",
    "irren": "in + DAT",
    "kämpfen": "für + AKK, gegen + AKK",
    "klagen": "über + AKK",
    "kommen": "zu + DAT",
    "konzentrieren": "auf + AKK",
    "kümmern": "um + AKK",
    "lachen": "über + AKK",
    "leben": "von + DAT",
    "leiden": "an + DAT, unter + DAT",
    "liegen": "an + DAT",
    "machen": "zu + DAT",
    "mangeln": "an + DAT",
    "nachdenken": "über + AKK",
    "neigen": "zu + DAT",
    "orientieren": "an + DAT",
    "passen": "zu + DAT",
    "protestieren": "gegen + AKK",
    "rächen": "an + DAT, für + AKK",
    "ranken": "um + AKK",
    "raten": "zu + DAT",
    "reagieren": "auf + AKK",
    "rechnen": "mit + DAT",
    "reden": "mit + DAT, über + AKK",
    "richten": "an + AKK, nach + DAT",
    "riechen": "nach + DAT",
    "schimpfen": "auf + AKK",
    "schmecken": "nach + DAT",
    "schreiben": "an + AKK",
    "schützen": "vor + DAT",
    "sehen": "als + AKK",
    "sehnen": "nach + DAT",
    "senken": "um + AKK",
    "sinken": "um + AKK",
    "sorgen": "für + AKK",
    "sorgen": "um + AKK",
    "sprechen": "mit + DAT, über + AKK",
    "stammen": "aus + DAT",
    "staunen": "über + AKK",
    "steigen": "um + AKK",
    "sterben": "an + DAT",
    "stimmen": "für + AKK, gegen + AKK",
    "streiten": "mit + DAT, über + AKK",
    "suchen": "nach + DAT",
    "täuschen": "in + DAT",
    "teilnehmen": "an + DAT",
    "telefonieren": "mit + DAT",
    "träumen": "von + DAT",
    "überreden": "zu + DAT",
    "übersetzen": "aus + DAT, in + AKK",
    "überzeugen": "von + DAT",
    "umstellen": "auf + AKK",
    "einstellen": "auf + AKK",
    "unterhalten": "mit + DAT",
    "unterscheiden": "von + DAT",
    "verbergen": "vor + DAT",
    "verheimlichen": "vor + DAT",
    "verbinden": "mit + DAT",
    "verfügen": "über + AKK",
    "verklagen": "auf + AKK",
    "verlassen": "auf + AKK",
    "verleiten": "zu + DAT",
    "verlieben": "in + AKK",
    "verstehen": "unter + DAT",
    "verstoßen": "gegen + AKK",
    "vertiefen": "in + AKK",
    "vertrauen": "auf + AKK",
    "verzichten": "auf + AKK",
    "vorbereiten": "auf + AKK",
    "warnen": "vor + DAT",
    "warten": "auf + AKK",
    "wehren": "gegen + AKK",
    "werben": "für + AKK",
    "wissen": "über + AKK",
    "wundern": "über + AKK",
    "zählen": "zu + DAT",
    "zurückführen": "auf + AKK",
    "zweifeln": "an + DAT",
    "zwingen": "zu + DAT"
}
adjectives_with_prepositional_case = {
    "abhängig": "von + DAT",
    "adressiert": "an + AKK",
    "anerkannt": "als + NOM",
    "angewiesen": "auf + AKK",
    "aufgeschlossen": "gegenüber + DAT",
    "beeindruckt": "von + DAT",
    "befreundet": "mit + DAT",
    "begeistert": "von + DAT",
    "bekannt": "als + NOM, bei + DAT, für + AKK",
    "beliebt": "bei + DAT",
    "bereit": "zu + DAT",
    "beschäftigt": "mit + DAT",
    "besorgt": "um + AKK",
    "beteiligt": "an + DAT",
    "beunruhigt": "über + AKK",
    "bewandert": "auf + DAT, in + DAT",
    "blass": "vor + DAT",
    "böse": "auf + AKK",
    "charakteristisch": "für + AKK",
    "dankbar": "für + AKK",
    "eifersüchtig": "auf + AKK",
    "einverstanden": "mit + DAT",
    "entfernt": "von + DAT",
    "entscheidend": "für + AKK",
    "entsetzt": "über + AKK",
    "enttäuscht": "von + DAT",
    "erfahren": "in + DAT",
    "erfreut": "über + AKK",
    "erstaunt": "über + AKK",
    "fähig": "zu + DAT",
    "fertig": "mit + DAT",
    "frei": "von + DAT",
    "freundlich": "zu + DAT",
    "froh": "über + DAT",
    "geeignet": "für + AKK",
    "geschickt": "in + DAT",
    "gespannt": "auf + AKK",
    "gewöhnt": "an + AKK",
    "glücklich": "über + AKK",
    "gut": "zu + DAT, in + AKK",
    "immun": "gegen + AKK",
    "interessiert": "an + DAT",
    "misstrauisch": "gegenüber + DAT",
    "müde": "von + DAT",
    "nachlässig": "in + DAT",
    "nett": "zu + DAT",
    "neugierig": "auf + AKK",
    "nützlich": "für + AKK",
    "reich": "an + DAT",
    "schädlich": "für + AKK",
    "schuld": "an + DAT",
    "stolz": "auf + AKK",
    "stumm": "vor + DAT",
    "traurig": "über + AKK",
    "überzeugt": "von + DAT",
    "unterteilt": "in + AKK",
    "verantwortlich": "für + AKK",
    "verärgert": "über + AKK",
    "verliebt": "in + AKK",
    "verrückt": "nach + DAT",
    "verwandt": "mit + DAT",
    "verwundert": "über + AKK",
    "wichtig": "für + AKK",
    "wütend": "auf + AKK, über + AKK",
    "zufrieden": "mit + DAT",
    "zurückhaltend": "gegenüber + DAT",
    "zuständig": "für + AKK"
}


noun_verb_combinations = {
    "Abhängigkeit": "in Abhängigkeit befinden; von etwas abhängen",
    "Ablehnung": "auf Ablehnung stoßen",
    "Abschied": "Abschied nehmen; verabschieden",
    "Abschluss": "einen Abschluss finden; abgeschlossen werden",
    "Absprache": "eine Absprache treffen; etwas absprechen",
    "Anerkennung": "Anerkennung finden/genießen; anerkannt werden",
    "Anfang": "den Anfang machen; etwas anfangen",
    "Anklage": "Anklage erheben; jemanden anklagen",
    "Anspruch": "Anspruch haben/erheben auf; Ansprüche stellen an; etwas beanspruchen",
    "Anstrengungen": "Anstrengungen unternehmen; anstrengen",
    "Anstoß": "Anstoß nehmen an",
    "Antrag": "einen Antrag stellen; etwas beantragen",
    "Anwendung": "zur Anwendung kommen; etwas anwenden",
    "Aufregung": "in Aufregung versetzen; in Aufregung geraten",
    "Auftrag": "einen Auftrag geben/erteilen; einen Auftrag bekommen/erhalten",
    "Auge": "etwas/jemanden im Auge haben/behalten",
    "Auskunft": "Auskunft erteilen/geben",
    "Beachtung": "Beachtung finden; etwas beachten",
    "Beitrag": "einen Beitrag leisten zu; etwas beitragen",
    "Beobachtung": "unter Beobachtung stehen; beobachtet werden",
    "Berücksichtigung": "Berücksichtigung finden; etwas berücksichtigen",
    "Beschluss": "einen Beschluss fassen; etwas beschließen",
    "Beschwerde": "Beschwerde einlegen/erheben; offiziell beschweren",
    "Betracht": "etwas in Betracht ziehen; etwas erwägen/überlegen",
    "Bewegung": "in Bewegung geraten/kommen; bewegen",
    "Beweis": "unter Beweis stellen; einen Beweis erbringen/führen",
    "Bezug": "Bezug nehmen auf",
    "Bilanz": "Bilanz ziehen; etwas abschließen",
    "Diskussion": "etwas zur Diskussion stellen; zur Diskussion stehen",
    "Druck": "jemanden unter Druck setzen; unter Druck stehen",
    "Eindruck": "einen Eindruck machen/hinterlassen; einen Eindruck gewinnen/haben; Eindruck schinden; einen Eindruck erwecken",
    "Einfluss": "Einfluss ausüben/nehmen/haben auf; unter dem Einfluss stehen",
    "Einigung": "eine Einigung erzielen; einigen",
    "Einsicht": "Einsicht nehmen in; etwas einsehen",
    "Empfang": "in Empfang nehmen; jemanden empfangen",
    "Entscheidung": "eine Entscheidung treffen; entscheiden",
    "Entschluss": "einen Entschluss fassen; zu etwas entschließen",
    "Erfüllung": "in Erfüllung gehen; erfüllt werden",
    "Erinnerungen": "Erinnerungen wecken; jemanden an etwas erinnern",
    "Erklärung": "eine Erklärung abgeben; etwas erklären erläutern",
    "Erlaubnis": "eine Erlaubnis erteilen/geben; jemandem etwas erlauben",
    "Erstaunen": "in Erstaunen versetzen; jemanden erstaunen",
    "Erwägung": "in Erwägung ziehen; etwas erwägen",
    "Fehler": "einen Fehler begehen/machen; einen Fehler einräumen/zugeben/einsehen/erkennen",
    "Folge": "zur Folge haben; aus etwas folgen",
    "Forderung": "eine Forderung stellen; etwas fordern",
    "Frage": "eine Frage stellen; etwas fragen",
    "Gefahr": "in Gefahr bringen; in Gefahr schweben/sein/in Gefahr befinden",
    "Gegensatz": "im Gegensatz stehen zu",
    "Gesellschaft": "Gesellschaft leisten; jemanden begleiten",
    "Gespräch": "ein Gespräch führen; sprechen",
    "Handel": "Handel treiben; mit etwas handeln",
    "Hilfe": "Hilfe leisten; jemandem helfen",
    "Hinweis": "einen Hinweis geben; jemanden auf etwas hinweisen",
    "Hoffnung": "die Hoffnung haben/hegen; sich/jemandem Hoffnung machen; auf etwas hoffen",
    "Interesse": "Interesse zeigen; interessiert sein; Interesse wecken",
    "Irrtum": "im Irrtum befinden; irren",
    "Kauf": "etwas in Kauf nehmen; etwas akzeptieren müssen",
    "Kenntnis": "jemanden in Kenntnis setzen; etwas zur Kenntnis nehmen; jemanden informieren; etwas wahrnehmen",
    "Klärung": "im Klaren sein über; etwas wissen über",
    "Kompromiss": "einen Kompromiss schließen; einigen",
    "Kontakt": "Kontakt aufnehmen mit; jemanden kontaktieren",
    "Kraft": "in Kraft treten; gültig werden; außer Kraft setzen",
    "Kritik": "Kritik üben an; kritisieren; auf Kritik stoßen; kritisiert werden",
    "Laufenden": "auf dem Laufenden sein; informiert werden; jemanden auf dem Laufenden halten; jemanden informieren",
    "Lösung": "eine Lösung finden; etwas lösen",
    "Maßnahmen": "Maßnahmen treffen/ergreifen/durchführen; handeln",
    "Meinung": "eine Meinung vertreten; etwas meinen",
    "Nachforschungen": "Nachforschungen anstellen; untersuchen/nachforschen",
    "Öffentlichkeit": "an die Öffentlichkeit geraten; veröffentlicht werden",
    "Platz": "Platz nehmen; setzen",
    "Protokoll": "Protokoll führen/schreiben; protokollieren",
    "Prüfung": "etwas einer Prüfung unterziehen; etwas prüfen/kontrollieren",
    "Rat": "einen Rat erteilen/geben; jemanden zu Rate ziehen; jemandem etwas raten",
    "Rechenschaft": "Rechenschaft ablegen; über Vergangenes informieren; jemanden zur Rechenschaft ziehen; jemanden verantwortlich machen",
    "Rechnung": "in Rechnung stellen; jemandem etwas berechnen",
    "Rede": "eine Rede halten; reden; jemanden zur Rede stellen; jemanden zur Erklärung auffordern",
    "Rücksicht": "Rücksicht nehmen auf; die Interessen anderer beachten/etwas berücksichtigen",
    "Sicht": "in Sicht sein; erwartet werden",
    "Sprache": "zur Sprache bringen; etwas be-/ansprechen; zur Sprache kommen; besprochen werden",
    "Stellung": "Stellung nehmen; etwas begründen",
    "Strafe": "etwas unter Strafe stellen; bestraft werden; unter Strafe stehen",
    "Streik": "in Streik treten; streiken",
    "Überlegungen": "Überlegungen anstellen; nachdenken/überlegen",
    "Unterstützung": "Unterstützung genießen/finden; unterstützt werden",
    "Urteil": "ein Urteil fällen; etwas beurteilen; Recht sprechen",
    "Verantwortung": "Verantwortung übernehmen für; verantwortlich zeigen; Verantwortung tragen für; verantwortlich sein; jemanden zur Verantwortung ziehen; jemanden für etwas verantwortlich machen",
    "Verbesserungen": "Verbesserungen durchführen/vornehmen; verbessern",
    "Verbindung": "in Verbindung setzen mit; jemanden kontaktieren; in Verbindung stehen; Kontakt haben",
    "Verbrechen": "ein Verbrechen begehen/verüben; kriminell handeln",
    "Verdacht": "Verdacht hegen/schöpfen; jemanden verdächtigen; unter Verdacht stehen; verdächtigt werden",
    "Vereinbarung": "eine Vereinbarung treffen; etwas vereinbaren",
    "Verfügung": "zur Verfügung stellen; etwas bereitstellen; zur Verfügung stehen; gebraucht werden können",
    "Verhandlungen": "Verhandlungen führen; verhandeln",
    "Verständnis": "Verständnis haben/zeigen; etwas verstehen",
    "Versuch": "einen Versuch unternehmen; etwas versuchen",
    "Verwendung": "Verwendung finden; verwendet werden",
    "Verzweiflung": "jemanden zur Verzweiflung bringen; jemanden verrückt machen",
    "Vorbereitungen": "Vorbereitungen treffen; etwas vorbereiten",
    "Vorwurf": "jemandem einen Vorwurf machen/einen Vorwurf erheben; jemandem etwas vorwerfen",
    "Wahl": "eine Wahl treffen; etwas wählen",
    "Erklärung": "eine Erklärung abgeben; etwas erklären/erläutern",
    "Erwägung": "in Erwägung ziehen; etwas erwägen/über etwas nachdenken",
    "Prüfung": "etwas einer Prüfung unterziehen; etwas prüfen/kontrollieren",
    "Verbrechen": "ein Verbrechen begehen/verüben; kriminell handeln",
    "Hinweis": "einen Hinweis geben; jemanden auf etwas hinweisen",

}

verbs_with_prepositional_case2 = {
    "abbringen": "von + DAT",
    "abgeben": "mit + DAT",
    "abhalten": "von + DAT",
    "abhängen": "von + DAT",
    "abhärten": "gegen + AKK",
    "absehen": "von + DAT",
    "achten": "auf + AKK",
    "ändern": "an + DAT",
    "anfangen": "mit + DAT",
    "ängstigen": "vor + DAT, um + AKK",
    "anpassen": "an + AKK",
    "anregen": "zu + DAT",
    "anrufen": "bei + DAT",
    "ansehen": "als + AKK",
    "antworten": "auf + AKK",
    "arbeiten": "bei + DAT, als + NOM, an + DAT",
    "ärgern": "über + AKK",
    "auffordern": "zu + DAT",
    "aufhören": "mit + DAT",
    "aufpassen": "auf + AKK",
    "aufregen": "über + AKK",
    "ausdrücken": "in + DAT, mit + DAT",
    "auseinandersetzen": "mit + DAT",
    "ausgeben": "für + AKK",
    "ausgehen": "von + DAT",
    "aussehen": "nach + DAT",
    "aussprechen": "gegen + AKK, für + AKK, mit + DAT",
    "basieren": "auf + DAT",
    "bedanken": "bei + DAT, für + AKK",
    "beeilen": "mit + DAT",
    "befördern": "zu + DAT",
    "befreien": "von + DAT, aus + DAT",
    "umstellen": "auf + AKK",
    "einstellen": "auf + AKK",
    "unterhalten": "mit + DAT, über + AKK",
    "unterscheiden": "von + DAT, in + DAT, durch + AKK",
    "verbergen": "vor + DAT",
    "verheimlichen": "vor + DAT",
    "verbinden": "mit + DAT",
    "verfügen": "über + AKK",
    "verklagen": "auf + AKK",
    "verlassen": "auf + AKK",
    "verleiten": "zu + DAT",
    "verlieben": "in + AKK",
    "verstehen": "unter + DAT",
    "verstoßen": "gegen + AKK",
    "vertiefen": "in + AKK",
    "vertrauen": "auf + AKK",
    "verzichten": "auf + AKK",
    "vorbereiten": "auf + AKK",
    "warnen": "vor + DAT",
    "warten": "auf + AKK",
    "wehren": "gegen + AKK",
    "werben": "für + AKK",
    "wissen": "von + DAT, über + AKK",
    "wundern": "über + AKK",
    "zählen": "zu + DAT",
    "zurückführen": "auf + AKK",
    "zweifeln": "an + DAT",
    "zwingen": "zu + DAT",
    "rächen": "an + DAT, für + AKK",
    "ranken": "um + AKK",
    "raten": "zu + DAT",
    "reagieren": "auf + AKK",
    "rechnen": "mit + DAT",
    "reden": "mit + DAT, über + AKK",
    "richten": "an + AKK",
    "riechen": "nach + DAT",
    "schimpfen": "auf + AKK",
    "schmecken": "nach + DAT",
    "schreiben": "an + DAT",
    "schützen": "vor + DAT",
    "sehen": "als + AKK, Inf. mit zu",
    "sehnen": "nach + DAT",
    "senken": "um + AKK, auf + AKK",
    "sinken": "um + AKK, auf + AKK",
    "sorgen": "für + AKK",
    "sorgen": "um + AKK",
    "sprechen": "mit + DAT, über + AKK, von + DAT",
    "stammen": "aus + DAT",
    "staunen": "über + AKK",
    "steigen": "um + AKK, auf + AKK",
    "sterben": "an + AKK",
    "stimmen": "für + AKK, gegen + AKK",
    "streiten": "mit + DAT, über + AKK",
    "suchen": "nach + DAT",
    "täuschen": "in + DAT",
    "teilnehmen": "an + DAT",
    "telefonieren": "mit + DAT",
    "träumen": "von + DAT",
    "überreden": "zu + DAT",
    "übersetzen": "aus + DAT, in + AKK",
    "überzeugen": "von + DAT",
    "umstellen": "auf + AKK",
    "einstellen": "auf + AKK",
    "unterhalten": "mit + DAT, über + AKK",
    "unterscheiden": "von + DAT, in + DAT, durch + AKK",
    "verbergen": "vor + DAT",
    "verheimlichen": "vor + DAT",
    "verbinden": "mit + DAT",
    "verfügen": "über + AKK",
    "verklagen": "auf + AKK",
    "verlassen": "auf + AKK",
    "verleiten": "zu + DAT",
    "verlieben": "in + AKK",
    "verstehen": "unter + DAT",
    "verstoßen": "gegen + AKK",
    "vertiefen": "in + AKK",
    "vertrauen": "auf + AKK",
    "verzichten": "auf + AKK",
    "vorbereiten": "auf + AKK",
    "warnen": "vor + DAT",
    "warten": "auf + AKK",
    "wehren": "gegen + AKK",
    "werben": "für + AKK",
    "wissen": "von + DAT, über + AKK",
    "wundern": "über + AKK",
    "zählen": "zu + DAT",
    "zurückführen": "auf + AKK",
    "zweifeln": "an + DAT",
    "zwingen": "zu + DAT",
    "rächen": "an + DAT, für + AKK",
    "ranken": "um + AKK",
    "raten": "zu + DAT",
    "reagieren": "auf + AKK",
    "rechnen": "mit + DAT",
    "reden": "mit + DAT, über + AKK",
    "richten": "an + AKK",
    "riechen": "nach + DAT",
    "schimpfen": "auf + AKK",
    "schmecken": "nach + DAT",
    "schreiben": "an + DAT",
    "schützen": "vor + DAT",
    "sehen": "als + AKK, Inf. mit zu",
    "sehnen": "nach + DAT",
    "senken": "um + AKK, auf + AKK",
    "sinken": "um + AKK, auf + AKK",
    "sorgen": "für + AKK",
    "sorgen": "um + AKK",
    "sprechen": "mit + DAT, über + AKK, von + DAT",
    "stammen": "aus + DAT",
    "staunen": "über + AKK",
    "steigen": "um + AKK, auf + AKK",
    "sterben": "an + AKK",
    "stimmen": "für + AKK, gegen + AKK",
    "streiten": "mit + DAT, über + AKK",
    "suchen": "nach + DAT",
    "täuschen": "in + DAT",
    "teilnehmen": "an + DAT",
    "telefonieren": "mit + DAT",
    "träumen": "von + DAT",
    "überreden": "zu + DAT",
    "übersetzen": "aus + DAT, in + AKK",
    "überzeugen": "von + DAT"
}


irregular_verbs = {
    "haben": "hat — hatte — hat gehabt",
    "sein": "ist — war — ist gewesen",
    "werden": "wird — wurde — ist geworden",
        "dürfen": "darf — durfte — hat gedurft",
    "können": "kann — konnte — hat gekonnt",
    "mögen": "mag — mochte — hat gemocht",
    "müssen": "muss — musste — hat gemusst",
    "sollen": "soll — sollte — hat gesollt",
    "wollen": "will — wollte — hat gewollt",
    
        "backen": "bäckt — backte/buk — hat gebacken",
    "befehlen": "befiehlt — befahl — hat befohlen",
    "beginnen": "beginnt — begann — hat begonnen",
    "beißen": "beißt — biss — hat gebissen",
    "bergen": "birgt — barg — hat geborgen",
    "bersten": "birst — barst — ist geborsten",
    "betrügen": "betrügt — betrog — hat betrogen",
    "bewegen": "bewegt — bewog — hat bewogen",
    "biegen": "biegt — bog — hat gebogen",
    "bieten": "bietet — bot — hat geboten",
    "binden": "bindet — band — hat gebunden",
    "bitten": "bittet — bat — hat gebeten",
    "blasen": "bläst — blies — hat geblasen",
    "bleiben": "bleibt — blieb — ist geblieben",
    "braten": "brät — briet — hat gebraten",
    "brechen": "bricht — brach — hat/ist gebrochen",
    "brennen": "brennt — brannte — hat gebrannt",
    "bringen": "bringt — brachte — hat gebracht",
    "denken": "denkt — dachte — hat gedacht",
    "dingen": "dingt — dingte/dang — hat gedingt/gedungen",
    "dreschen": "drischt — drosch — hat gedroschen",
    "dringen": "dringt — drang — ist/hat gedrungen",
    "empfehlen": "empfiehlt — empfahl — hat empfohlen",
    "erlöschen": "erlischt — erlosch — ist erloschen",
    "erschrecken": "erschrickt — erschrak — ist erschrocken",
    "erwägen": "erwägt — erwog — hat erwogen",
    "essen": "isst — aß — hat gegessen",
    "fahren": "fährt — fuhr — ist/hat gefahren",
    "fallen": "fällt — fiel — ist gefallen",
    "fangen": "fängt — fing — hat gefangen",
    "fechten": "ficht — focht — hat gefochten",
    "finden": "findet — fand — hat gefunden",
    "fliegen": "fliegt — flog — ist/hat geflogen",
    "fliehen": "flieht — floh — ist geflohen",
    "fließen": "fließt — floss — ist geflossen",
    "fressen": "frisst — fraß — hat gefressen",
    "frieren": "friert — fror — hat/ist gefroren",
    "gären": "gärt — gor/gärte — ist gegoren/gegärt",
    "gebären": "gebärt/gebiert — gebar — hat geboren",
    "geben": "gibt — gab — hat gegeben",
    "gedeihen": "gedeiht — gedieh — ist gediehen",
    "gehen": "geht — ging — ist gegangen",
    "gelingen": "gelingt — gelang — ist gelungen",
    "gelten": "gilt — galt — hat gegolten",
    "genesen": "genest — genas — ist genesen",
    "genießen": "genießt — genoss — hat genossen",
    "geraten": "gerät — geriet — ist geraten",
    "geschehen": "geschieht — geschah — ist geschehen",
    "gewinnen": "gewinnt — gewann — hat gewonnen",
    "gießen": "gießt — goss — hat gegossen",
    "gleichen": "gleicht — glich — hat geglichen",
    "gleiten": "gleitet — glitt — ist geglitten",
    "glimmen": "glimmt — glomm/glimmte — hat geglommen/geglimmt",
    "graben": "gräbt — grub — hat gegraben",
      "greifen": "greift — griff — hat gegriffen",
    "halten": "hält — hielt — hat gehalten",
    "hängen": "hängt — hing — hat gehangen",
    "hauen": "haut — haute/hieb — hat gehauen",
    "heben": "hebt — hob — hat gehoben",
    "heißen": "heißt — hieß — hat geheißen",
    "helfen": "hilft — half — hat geholfen",
    "kennen": "kennt — kannte — hat gekannt",
    "klimmen": "klimmt — klomm/klimmte — ist geklommen/geklimmt",
    "klingen": "klingt — klang — hat geklungen",
    "kneifen": "kneift — kniff — hat gekniffen",
    "kommen": "kommt — kam — ist gekommen",
    "kriechen": "kriecht — kroch — ist gekrochen",
    "laden": "lädt — lud — hat geladen",
    "lassen": "lässt — ließ — hat gelassen",
    "laufen": "läuft — lief — ist gelaufen",
    "leiden": "leidet — litt — hat gelitten",
    "leihen": "leiht — lieh — hat geliehen",
    "lesen": "liest — las — hat gelesen",
    "liegen": "liegt — lag — hat gelegen",
    "lügen": "lügt — log — hat gelogen",
    "mahlen": "mahlt — mahlte — hat gemahlen",
    "meiden": "meidet — mied — hat gemieden",
    "melken": "melkt — molk/melkte — hat gemolken/gemelkt",
    "messen": "misst — maß — hat gemessen",
    "nehmen": "nimmt — nahm — hat genommen",
    "nennen": "nennt — nannte — hat genannt",
    "pfeifen": "pfeift — pfiff — hat gepfiffen",
    "preisen": "preist — pries — hat gepriesen",
    "quellen": "quillt — quoll — ist gequollen",
    "raten": "rät — riet — hat geraten",
    "reiben": "reibt — rieb — hat gerieben",
    "reißen": "reißt — riss — ist/hat gerissen",
    "reiten": "reitet — ritt — ist geritten",
    "rennen": "rennt — rannte — ist gerannt",
    "riechen": "riecht — roch — hat gerochen",
    "ringen": "ringt — rang — hat gerungen",
    "rinnen": "rinnt — rann — ist geronnen",
    "rufen": "ruft — rief — hat gerufen",
    "salzen": "salzt — salzte — hat gesalzen",
    "saufen": "säuft — soff — hat gesoffen",
    "saugen": "saugt — sog — hat gesogen",
    "schaffen": "schafft — schuf — hat geschaffen",
    "scheiden": "scheidet — schied — hat geschieden",
    "scheinen": "scheint — schien — hat geschienen",
    "scheren": "schert — schor — hat geschoren",
    "schieben": "schiebt — schob — hat geschoben",
    "schießen": "schießt — schoss — hat geschossen",
    "schlafen": "schläft — schlief — hat geschlafen",
    "schlagen": "schlägt — schlug — hat geschlagen",
    "schleichen": "schleicht — schlich — ist geschlichen",
    "schleifen": "schleift — schliff — hat geschliffen",
    "schließen": "schließt — schloss — hat geschlossen",
    "schlingen": "schlingt — schlang — hat geschlungen",
    "schmeißen": "schmeißt — schmiss — hat geschmissen",
    "schmelzen": "schmilzt — schmolz — ist/hat geschmolzen",
        "schneiden": "schneidet — schnitt — hat geschnitten",
    "schreiben": "schreibt — schrieb — hat geschrieben",
    "schreien": "schreit — schrie — hat geschrien",
    "schreiten": "schreitet — schritt — ist geschritten",
    "schweigen": "schweigt — schwieg — hat geschwiegen",
    "schwellen": "schwillt — schwoll — ist geschwollen",
    "schwimmen": "schwimmt — schwamm — ist geschwommen",
    "schwingen": "schwingt — schwang — hat geschwungen",
    "schwören": "schwört — schwor — hat geschworen",
    "sehen": "sieht — sah — hat gesehen",
    "senden": "sendet — sandte — hat gesandt",
    "singen": "singt — sang — hat gesungen",
    "sinken": "sinkt — sank — ist gesunken",
    "sinnen": "sinnt — sann — hat gesonnen",
    "sitzen": "sitzt — saß — hat gesessen",
    "spalten": "spaltet — spaltete — hat gespalten",
    "speien": "speit — spie — hat gespien",
    "spinnen": "spinnt — spann — hat gesponnen",
    "sprechen": "spricht — sprach — hat gesprochen",
    "sprießen": "sprießt — spross — ist gesprossen",
    "springen": "springt — sprang — ist gesprungen",
    "stechen": "sticht — stach — hat gestochen",
    "stehen": "steht — stand — hat gestanden",
    "stehlen": "stiehlt — stahl — hat gestohlen",
    "steigen": "steigt — stieg — ist gestiegen",
    "sterben": "stirbt — starb — ist gestorben",
    "stieben": "stiebt — stob — ist gestoben",
    "stinken": "stinkt — stank — hat gestunken",
    "stoßen": "stößt — stieß — hat/ist gestoßen",
    "streichen": "streicht — strich — hat gestrichen",
    "streiten": "streitet — stritt — hat gestritten",
    "tragen": "trägt — trug — hat getragen",
    "treffen": "trifft — traf — hat getroffen",
    "treiben": "treibt — trieb — hat getrieben",
    "treten": "tritt — trat — ist/hat getreten",
    "trinken": "trinkt — trank — hat getrunken",
    "tun": "tut — tat — hat getan",
    "verderben": "verdirbt — verdarb — hat/ist verdorben",
    "verdrießen": "verdrießt — verdross — hat verdrossen",
    "vergessen": "vergisst — vergaß — hat vergessen",
    "verlieren": "verliert — verlor — hat verloren",
    "verschwinden": "verschwindet — verschwand — ist verschwunden",
    "verzeihen": "verzeiht — verzieh — hat verziehen",
    "wachsen": "wächst — wuchs — ist gewachsen",
    "waschen": "wäscht — wusch — hat gewaschen",
    "weichen": "weicht — wich — ist gewichen",
    "weisen": "weist — wies — hat gewiesen",
    "wenden": "wendet — wandte — hat gewandt",
    "werben": "wirbt — warb — hat geworben",
    "werfen": "wirft — warf — hat geworfen",
    "wiegen": "wiegt — wog — hat gewogen",
    "winden": "windet — wand — hat gewunden",
    "wissen": "weiß — wusste — hat gewusst",
    "wringen": "wringt — wrang — hat gewrungen",
    "ziehen": "zieht — zog — hat/ist gezogen",
    "zwingen": "zwingt — zwang — hat gezwungen",
    "wenden": "wendet — wandte — hat gewandt",
    "werben": "wirbt — warb — hat geworben",
    "werfen": "wirft — warf — hat geworfen",
    "wiegen": "wiegt — wog — hat gewogen",
    "winden": "windet — wand — hat gewunden",
    "wissen": "weiß — wusste — hat gewusst",
    "wringen": "wringt — wrang — hat gewrungen",
    "ziehen": "zieht — zog — hat gezogen",
    "zwingen": "zwingt — zwang — hat gezwungen"
}
 

class deChunks:
    def __init__(self, document: spacy.tokens.doc.Doc):
        self.document = document
        self.irregular_verbs = set(irregular_verbs.keys())
        self.verben_mit_direktem_kasus = set(verben_mit_direktem_kasus.keys())
        self.adjectives_with_prepositional_case = set(adjectives_with_prepositional_case.keys())
        self.noun_verb_combinations = set(noun_verb_combinations.keys())
        
        self.verbs_with_prepositional_case = set(verbs_with_prepositional_case.keys())
        self.verbs_with_prepositional_case2 = set(verbs_with_prepositional_case2.keys())
    
        
        
        self.chunks = list(self.process())

    def process(self):
        for token in self.document:
            if token.lemma_.lower() in self.irregular_verbs and token.pos_ in {"VERB", "AUX", "ADV"}:
                verb_forms = irregular_verbs[token.lemma_.lower()]
                yield f"{token.lemma_.lower()} — {verb_forms}"
                
            if token.lemma_.lower() in self.verben_mit_direktem_kasus and token.pos_ in {"VERB", "AUX", "ADV"}:
                verb_forms = verben_mit_direktem_kasus[token.lemma_.lower()]
                yield f"{token.lemma_.lower()} + {verb_forms}"
                
                
            if token.lemma_.lower() in self.verbs_with_prepositional_case and token.pos_ in {"VERB", "AUX", "ADV"}:
                verb_forms = verbs_with_prepositional_case[token.lemma_.lower()]
                yield f"{token.lemma_.lower()} + {verb_forms}"
                
            if token.lemma_ in self.noun_verb_combinations and token.pos_ in {"NOUN"}:
                verb_forms = noun_verb_combinations[token.lemma_]
                yield f"{verb_forms}"
                
            if token.lemma_.lower() in self.verbs_with_prepositional_case and token.pos_ in {"VERB", "AUX", "ADV"}:
                verb_forms = verbs_with_prepositional_case[token.lemma_.lower()]
                yield f"{token.lemma_.lower()} + {verb_forms}"

        
            if token.lemma_.lower() in self.adjectives_with_prepositional_case and token.pos_ in {"ADJD"}:
                verb_forms = adjectives_with_prepositional_case[token.lemma_.lower()]
                yield f"{token.lemma_.lower()} + {verb_forms}"
                
            if token.lemma_.lower() in self.verbs_with_prepositional_case2 and token.pos_ in {"VERB", "AUX", "ADV"}:
                verb_forms = verbs_with_prepositional_case2[token.lemma_.lower()]
                yield f"{token.lemma_.lower()} + {verb_forms}"
                
        for chunk in self.document.noun_chunks:
            if len(chunk) > 2 and not chunk.text[0] in {'"', "'"}:
                yield chunk.text[0].lower() + chunk.text[1:]

    def get(self):
        return "^".join(self.chunks)
 