#!/usr/bin/env python3
"""Batch 2 authoring + merge tool: C1-readiness pattern extension.

Adds 24 patterns across 8 categories that target real C1 gaps (collocations,
verb+preposition government, reported speech, emphasis/inversion, hedging,
conversational chunks, abstract language, numbers/data/trends).

Same schema and 12-varied-examples-per-language convention as the original sets.
Appends to data/advanced-patterns.json (restore to 260 base before running).

Run:  python3 inbox/build_c1_patterns.py
"""
import json
from datetime import datetime, timezone

SRC = "data/advanced-patterns.json"
GEN_AT = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.") + "000Z"


def L(formula, example, translation, examples):
    return {
        "formula": formula,
        "example": example,
        "translation": translation,
        "examples": [{"text": t, "translation_ru": r} for (t, r) in examples],
    }


def P(pid, group, title_ru, metaphor_ru, en, de):
    return {
        "id": pid,
        "group_id": group,
        "title_ru": title_ru,
        "metaphor_ru": metaphor_ru,
        "langs": [dict(lang="en", **en), dict(lang="de", **de)],
        "formulas": [en["formula"], de["formula"]],
        "gen": {
            "status": "generated",
            "iterations": 1,
            "lastGeneratedAt": GEN_AT,
            "languages": ["en", "de"],
            "notes": "c1-readiness-batch-2",
        },
    }


NEW = [

    # ============================================================ COL — Collocations (verb + noun)
    P("COL001", "COL", "Принять / обосновать / оспорить решение",
      "Решение — не просто make a decision. У C1 целое семейство глаголов: reach, reverse, justify, stand by, challenge. Каждый даёт свой оттенок — от принятия до защиты.",
      L("reach / make / reverse / justify a decision",
        "We need to reach a decision by Friday.",
        "Нам нужно принять решение к пятнице.",
        [
            ("We need to **reach a decision** by Friday.", "Нам нужно принять решение к пятнице."),
            ("The board will **make a decision** next week.", "Совет примет решение на следующей неделе."),
            ("They may **reverse the decision** if the data changes.", "Они могут отменить решение, если данные изменятся."),
            ("She had to **justify her decision** to the team.", "Ей пришлось обосновать своё решение перед командой."),
            ("I will **stand by my decision**, whatever happens.", "Я буду стоять на своём решении, что бы ни случилось."),
            ("He decided to **challenge the decision** in court.", "Он решил оспорить решение в суде."),
            ("We should **delay the decision** until we have more data.", "Нам стоит отложить решение, пока не будет больше данных."),
            ("They finally **reached a decision** after hours of debate.", "Они наконец приняли решение после часов споров."),
            ("I cannot **make this decision** alone.", "Я не могу принять это решение в одиночку."),
            ("Have you **reached a decision** yet?", "Вы уже приняли решение?"),
            ("She refused to **reverse her decision**.", "Она отказалась отменять своё решение."),
            ("We must **justify every decision** we make.", "Мы должны обосновывать каждое своё решение."),
        ]),
      L("eine Entscheidung treffen / revidieren / begründen",
        "Wir müssen bis Freitag eine Entscheidung treffen.",
        "Нам нужно принять решение к пятнице.",
        [
            ("Wir müssen bis Freitag **eine Entscheidung treffen**.", "Нам нужно принять решение к пятнице."),
            ("Der Vorstand wird nächste Woche **eine Entscheidung treffen**.", "Совет примет решение на следующей неделе."),
            ("Sie können **die Entscheidung revidieren**, wenn sich die Daten ändern.", "Они могут отменить решение, если данные изменятся."),
            ("Sie musste **ihre Entscheidung** vor dem Team **begründen**.", "Ей пришлось обосновать своё решение перед командой."),
            ("Ich werde **zu meiner Entscheidung stehen**, was auch passiert.", "Я буду стоять на своём решении, что бы ни случилось."),
            ("Er beschloss, **die Entscheidung** vor Gericht **anzufechten**.", "Он решил оспорить решение в суде."),
            ("Wir sollten **die Entscheidung verschieben**, bis wir mehr Daten haben.", "Нам стоит отложить решение, пока не будет больше данных."),
            ("Sie **trafen** nach stundenlangen Debatten endlich **eine Entscheidung**.", "Они наконец приняли решение после часов споров."),
            ("Ich kann **diese Entscheidung** nicht allein **treffen**.", "Я не могу принять это решение в одиночку."),
            ("Haben Sie schon **eine Entscheidung getroffen**?", "Вы уже приняли решение?"),
            ("Sie weigerte sich, **ihre Entscheidung zu revidieren**.", "Она отказалась отменять своё решение."),
            ("Wir müssen **jede Entscheidung begründen**, die wir treffen.", "Мы должны обосновывать каждое своё решение."),
        ])),

    P("COL002", "COL", "Поднять / решить / озвучить опасение",
      "Concern тоже имеет своё семейство: raise (поднять), address (заняться), resolve (снять), voice (озвучить), dismiss (отмести). Правильный глагол делает речь естественной.",
      L("raise / address / resolve / voice a concern",
        "She raised a concern about the timeline.",
        "Она подняла опасение по поводу сроков.",
        [
            ("She **raised a concern** about the timeline.", "Она подняла опасение по поводу сроков."),
            ("We need to **address this concern** before launch.", "Нам нужно проработать это опасение до запуска."),
            ("They quickly **resolved the concern** with a clear answer.", "Они быстро сняли опасение чётким ответом."),
            ("He **voiced a concern** about the budget.", "Он озвучил опасение по поводу бюджета."),
            ("I want to **raise a concern** about the scope.", "Я хочу поднять опасение по поводу объёма."),
            ("The manager **addressed every concern** in the meeting.", "Руководитель проработал каждое опасение на встрече."),
            ("We should not **dismiss their concerns** so quickly.", "Нам не стоит так быстро отметать их опасения."),
            ("She **resolved my concern** in one email.", "Она сняла моё опасение одним письмом."),
            ("They **raised several concerns** during the review.", "Они подняли несколько опасений во время проверки."),
            ("Have you **addressed the concern** yet?", "Ты уже проработал это опасение?"),
            ("He **voiced a concern** that others shared.", "Он озвучил опасение, которое разделяли и другие."),
            ("We must **address this concern** seriously.", "Мы должны серьёзно отнестись к этому опасению."),
        ]),
      L("eine Sorge äußern / ein Anliegen ansprechen / Bedenken ausräumen",
        "Sie äußerte eine Sorge wegen des Zeitplans.",
        "Она подняла опасение по поводу сроков.",
        [
            ("Sie **äußerte eine Sorge** wegen des Zeitplans.", "Она подняла опасение по поводу сроков."),
            ("Wir müssen **dieses Anliegen** vor dem Start **ansprechen**.", "Нам нужно проработать это опасение до запуска."),
            ("Sie **räumten die Bedenken** mit einer klaren Antwort **aus**.", "Они быстро сняли опасение чётким ответом."),
            ("Er **äußerte Bedenken** wegen des Budgets.", "Он озвучил опасение по поводу бюджета."),
            ("Ich möchte **eine Sorge** zum Umfang **äußern**.", "Я хочу поднять опасение по поводу объёма."),
            ("Die Leitung **sprach jedes Anliegen** im Meeting **an**.", "Руководитель проработал каждое опасение на встрече."),
            ("Wir sollten **ihre Bedenken** nicht so schnell **abtun**.", "Нам не стоит так быстро отметать их опасения."),
            ("Sie **räumte meine Sorge** mit einer E-Mail **aus**.", "Она сняла моё опасение одним письмом."),
            ("Sie **äußerten mehrere Bedenken** während der Prüfung.", "Они подняли несколько опасений во время проверки."),
            ("Hast du **das Anliegen** schon **angesprochen**?", "Ты уже проработал это опасение?"),
            ("Er **äußerte eine Sorge**, die andere teilten.", "Он озвучил опасение, которое разделяли и другие."),
            ("Wir müssen **dieses Anliegen** ernsthaft **ansprechen**.", "Мы должны серьёзно отнестись к этому опасению."),
        ])),

    P("COL003", "COL", "Оценить / снизить / принять риск",
      "Risk работает с конкретными глаголами: assess (оценить), mitigate (снизить), accept (принять), pose (нести), run (идти на риск). Это основа любого разговора о решениях.",
      L("assess / mitigate / accept / pose a risk",
        "We need to assess the risk before we invest.",
        "Нам нужно оценить риск, прежде чем инвестировать.",
        [
            ("We need to **assess the risk** before we invest.", "Нам нужно оценить риск, прежде чем инвестировать."),
            ("They took steps to **mitigate the risk**.", "Они приняли меры, чтобы снизить риск."),
            ("We can **accept this risk**; it is small.", "Мы можем принять этот риск; он невелик."),
            ("This change could **pose a risk** to users.", "Это изменение может нести риск для пользователей."),
            ("She **assessed the risks** carefully.", "Она тщательно оценила риски."),
            ("We must **mitigate the risk** of failure.", "Мы должны снизить риск неудачи."),
            ("He decided to **run the risk** anyway.", "Он решил всё равно пойти на риск."),
            ("They **accepted the risk** and moved on.", "Они приняли риск и двинулись дальше."),
            ("The plan **poses a serious risk**.", "План несёт серьёзный риск."),
            ("Have you **assessed the risk** properly?", "Ты правильно оценил риск?"),
            ("We should **mitigate every risk** we can.", "Мы должны снизить каждый риск, который можем."),
            ("I am not willing to **run that risk**.", "Я не готов идти на такой риск."),
        ]),
      L("ein Risiko einschätzen / mindern / eingehen / bergen",
        "Wir müssen das Risiko einschätzen, bevor wir investieren.",
        "Нам нужно оценить риск, прежде чем инвестировать.",
        [
            ("Wir müssen **das Risiko einschätzen**, bevor wir investieren.", "Нам нужно оценить риск, прежде чем инвестировать."),
            ("Sie ergriffen Maßnahmen, um **das Risiko zu mindern**.", "Они приняли меры, чтобы снизить риск."),
            ("Wir können **dieses Risiko akzeptieren**; es ist gering.", "Мы можем принять этот риск; он невелик."),
            ("Diese Änderung könnte **ein Risiko für** die Nutzer **bergen**.", "Это изменение может нести риск для пользователей."),
            ("Sie **schätzte die Risiken** sorgfältig **ein**.", "Она тщательно оценила риски."),
            ("Wir müssen **das Risiko** eines Scheiterns **mindern**.", "Мы должны снизить риск неудачи."),
            ("Er beschloss, **das Risiko** trotzdem **einzugehen**.", "Он решил всё равно пойти на риск."),
            ("Sie **akzeptierten das Risiko** und machten weiter.", "Они приняли риск и двинулись дальше."),
            ("Der Plan **birgt ein ernstes Risiko**.", "План несёт серьёзный риск."),
            ("Hast du **das Risiko** richtig **eingeschätzt**?", "Ты правильно оценил риск?"),
            ("Wir sollten **jedes Risiko mindern**, das wir können.", "Мы должны снизить каждый риск, который можем."),
            ("Ich bin nicht bereit, **dieses Risiko einzugehen**.", "Я не готов идти на такой риск."),
        ])),

    # ============================================================ VRB — Verb + preposition government
    P("VRB001", "VRB", "Полагаться на / зависеть от",
      " rely on, depend on, count on — все с on, но с разными оттенками. Управление предлогом — классический разрыв между B2 и C1; ошибка здесь сразу выдаёт уровень.",
      L("rely on / depend on / count on + noun/gerund",
        "We rely on this tool every day.",
        "Мы полагаемся на этот инструмент каждый день.",
        [
            ("We **rely on** this tool every day.", "Мы полагаемся на этот инструмент каждый день."),
            ("You can **count on** me to finish it.", "Ты можешь рассчитывать на меня — я это закончу."),
            ("It **depends on** the budget.", "Это зависит от бюджета."),
            ("She **relies on** her team for support.", "Она полагается на свою команду в поддержке."),
            ("We **depend on** accurate data.", "Мы зависим от точных данных."),
            ("You should not **rely on** luck.", "Не стоит полагаться на удачу."),
            ("They **count on** us to deliver.", "Они рассчитывают, что мы справимся."),
            ("It all **depends on** the weather.", "Всё зависит от погоды."),
            ("I **rely on** clear deadlines.", "Я полагаюсь на чёткие сроки."),
            ("Can we **count on** your vote?", "Мы можем рассчитывать на твой голос?"),
            ("He **depends on** regular feedback.", "Он зависит от регулярной обратной связи."),
            ("We **rely on** each other to succeed.", "Мы полагаемся друг на друга, чтобы добиться успеха."),
        ]),
      L("sich verlassen auf / abhängen von / zählen auf",
        "Wir verlassen uns jeden Tag auf dieses Werkzeug.",
        "Мы полагаемся на этот инструмент каждый день.",
        [
            ("Wir **verlassen uns** jeden Tag **auf** dieses Werkzeug.", "Мы полагаемся на этот инструмент каждый день."),
            ("Du kannst **dich auf** mich **verlassen**, dass ich es fertig mache.", "Ты можешь рассчитывать на меня — я это закончу."),
            ("Es **hängt vom** Budget **ab**.", "Это зависит от бюджета."),
            ("Sie **verlässt sich auf** ihr Team.", "Она полагается на свою команду."),
            ("Wir **sind auf** genaue Daten **angewiesen**.", "Мы зависим от точных данных."),
            ("Du solltest **dich nicht auf** Glück **verlassen**.", "Не стоит полагаться на удачу."),
            ("Sie **zählen auf** uns, dass wir liefern.", "Они рассчитывают, что мы справимся."),
            ("Es **hängt ganz vom** Wetter **ab**.", "Всё зависит от погоды."),
            ("Ich **verlasse mich auf** klare Fristen.", "Я полагаюсь на чёткие сроки."),
            ("Können wir **auf** deine Stimme **zählen**?", "Мы можем рассчитывать на твой голос?"),
            ("Er **ist auf** regelmäßiges Feedback **angewiesen**.", "Он зависит от регулярной обратной связи."),
            ("Wir **verlassen uns aufeinander**, um erfolgreich zu sein.", "Мы полагаемся друг на друга, чтобы добиться успеха."),
        ])),

    P("VRB002", "VRB", "Объяснять / происходить из / приводить к",
      "account for, stem from, result in — три способа говорить о причинах через предлоги. Без них объяснения звучат плоско; с ними — точно и по-взрослому.",
      L("account for / stem from / result in + noun",
        "These factors account for most of the delay.",
        "Эти факторы объясняют большую часть задержки.",
        [
            ("These factors **account for** most of the delay.", "Эти факторы объясняют большую часть задержки."),
            ("The problem **stems from** poor planning.", "Проблема происходит из плохого планирования."),
            ("The change **resulted in** lower costs.", "Изменение привело к снижению расходов."),
            ("How do you **account for** this difference?", "Как ты объяснишь эту разницу?"),
            ("His success **stems from** hard work.", "Его успех происходит из упорного труда."),
            ("The error **resulted in** a data loss.", "Ошибка привела к потере данных."),
            ("Demand **accounts for** half of the growth.", "Спрос составляет половину роста."),
            ("The delay **stems from** a missing approval.", "Задержка происходит из-за отсутствующего согласования."),
            ("The merger **resulted in** new jobs.", "Слияние привело к новым рабочим местам."),
            ("This **accounts for** why sales fell.", "Это объясняет, почему продажи упали."),
            ("Her confidence **stems from** experience.", "Её уверенность происходит из опыта."),
            ("The policy **resulted in** more complaints.", "Политика привела к большему числу жалоб."),
        ]),
      L("erklären / herrühren von / führen zu / ausmachen",
        "Diese Faktoren erklären den Großteil der Verzögerung.",
        "Эти факторы объясняют большую часть задержки.",
        [
            ("Diese Faktoren **erklären** den Großteil der Verzögerung.", "Эти факторы объясняют большую часть задержки."),
            ("Das Problem **rührt von** schlechter Planung **her**.", "Проблема происходит из плохого планирования."),
            ("Die Änderung **führte zu** niedrigeren Kosten.", "Изменение привело к снижению расходов."),
            ("Wie **erklärst du** diesen Unterschied?", "Как ты объяснишь эту разницу?"),
            ("Sein Erfolg **rührt von** harter Arbeit **her**.", "Его успех происходит из упорного труда."),
            ("Der Fehler **führte zu** einem Datenverlust.", "Ошибка привела к потере данных."),
            ("Die Nachfrage **macht** die Hälfte des Wachstums **aus**.", "Спрос составляет половину роста."),
            ("Die Verzögerung **rührt von** einer fehlenden Freigabe **her**.", "Задержка происходит из-за отсутствующего согласования."),
            ("Die Fusion **führte zu** neuen Arbeitsplätzen.", "Слияние привело к новым рабочим местам."),
            ("Das **erklärt**, warum die Verkäufe fielen.", "Это объясняет, почему продажи упали."),
            ("Ihr Selbstvertrauen **rührt von** Erfahrung **her**.", "Её уверенность происходит из опыта."),
            ("Die Richtlinie **führte zu** mehr Beschwerden.", "Политика привела к большему числу жалоб."),
        ])),

    P("VRB003", "VRB", "Возражать против / настаивать на / обвинять в",
      "object to, insist on, accuse of — после них идёт герундий (doing). Это типичная ловушка: хочется поставить инфинитив, а нужно -ing. Частая ошибка именно на B2–C1.",
      L("object to / insist on / accuse someone of + gerund",
        "I object to working weekends without pay.",
        "Я возражаю против работы по выходным без оплаты.",
        [
            ("I **object to working** weekends without pay.", "Я возражаю против работы по выходным без оплаты."),
            ("She **insists on checking** everything twice.", "Она настаивает на том, чтобы проверять всё дважды."),
            ("They **accused him of breaking** the rules.", "Они обвинили его в нарушении правил."),
            ("We **object to changing** the terms now.", "Мы возражаем против изменения условий сейчас."),
            ("He **insists on being** involved.", "Он настаивает на том, чтобы быть вовлечённым."),
            ("She **accused them of hiding** the truth.", "Она обвинила их в сокрытии правды."),
            ("I **object to paying** extra fees.", "Я возражаю против оплаты дополнительных сборов."),
            ("They **insist on doing** it their way.", "Они настаивают на том, чтобы делать это по-своему."),
            ("He **accused her of lying** about the cost.", "Он обвинил её во лжи о стоимости."),
            ("Do you **object to waiting** a week?", "Ты возражаешь против того, чтобы подождать неделю?"),
            ("We **insist on getting** a clear answer.", "Мы настаиваем на получении чёткого ответа."),
            ("She **objected to being** blamed unfairly.", "Она возразила против того, чтобы её несправедливо обвиняли."),
        ]),
      L("etwas ablehnen / darauf bestehen, etw. zu tun / jmdn beschuldigen, etw. getan zu haben",
        "Ich lehne es ab, unbezahlt an Wochenenden zu arbeiten.",
        "Я возражаю против работы по выходным без оплаты.",
        [
            ("Ich **lehne es ab**, unbezahlt an Wochenenden **zu arbeiten**.", "Я возражаю против работы по выходным без оплаты."),
            ("Sie **besteht darauf**, alles zweimal **zu prüfen**.", "Она настаивает на том, чтобы проверять всё дважды."),
            ("Sie **beschuldigten ihn**, die Regeln **gebrochen zu haben**.", "Они обвинили его в нарушении правил."),
            ("Wir **lehnen es ab**, die Bedingungen jetzt **zu ändern**.", "Мы возражаем против изменения условий сейчас."),
            ("Er **besteht darauf**, einbezogen **zu werden**.", "Он настаивает на том, чтобы быть вовлечённым."),
            ("Sie **beschuldigte sie**, die Wahrheit **verschwiegen zu haben**.", "Она обвинила их в сокрытии правды."),
            ("Ich **lehne es ab**, zusätzliche Gebühren **zu zahlen**.", "Я возражаю против оплаты дополнительных сборов."),
            ("Sie **bestehen darauf**, es auf ihre Art **zu tun**.", "Они настаивают на том, чтобы делать это по-своему."),
            ("Er **beschuldigte sie**, über die Kosten **gelogen zu haben**.", "Он обвинил её во лжи о стоимости."),
            ("**Lehnst du es ab**, eine Woche **zu warten**?", "Ты возражаешь против того, чтобы подождать неделю?"),
            ("Wir **bestehen darauf**, eine klare Antwort **zu bekommen**.", "Мы настаиваем на получении чёткого ответа."),
            ("Sie **lehnte es ab**, unfair **beschuldigt zu werden**.", "Она возразила против того, чтобы её несправедливо обвиняли."),
        ])),

    # ============================================================ REP — Reported speech / citing others
    P("REP001", "REP", "Указать / утверждать / объяснить, что…",
      "C1 говорит не только от себя. point out, argue, explain that — нейтральная и поддерживающая передача чужой позиции. Без них любой анализ превращается в монолог.",
      L("point out / argue / explain that + clause",
        "She pointed out that the deadline was unrealistic.",
        "Она указала на то, что срок был нереалистичным.",
        [
            ("She **pointed out that** the deadline was unrealistic.", "Она указала на то, что срок был нереалистичным."),
            ("He **argued that** we should wait.", "Он утверждал, что нам стоит подождать."),
            ("They **explained that** the change was temporary.", "Они объяснили, что изменение временное."),
            ("She **pointed out that** the data was incomplete.", "Она указала на то, что данные неполные."),
            ("He **argued that** the cost was too high.", "Он утверждал, что стоимость слишком высока."),
            ("They **pointed out that** we had missed a step.", "Они указали на то, что мы пропустили шаг."),
            ("She **explained that** the delay was unavoidable.", "Она объяснила, что задержка была неизбежна."),
            ("He **pointed out that** this had happened before.", "Он указал на то, что такое уже случалось."),
            ("They **argued that** a smaller scope was safer.", "Они утверждали, что меньший объём безопаснее."),
            ("She **pointed out that** nobody owned the task.", "Она указала на то, что за задачу никто не отвечает."),
            ("He **explained that** the risk was low.", "Он объяснил, что риск невелик."),
            ("Did she **point out that** the plan had changed?", "Она указала на то, что план изменился?"),
        ]),
      L("darauf hinweisen / argumentieren / erklären, dass",
        "Sie wies darauf hin, dass der Termin unrealistisch war.",
        "Она указала на то, что срок был нереалистичным.",
        [
            ("Sie **wies darauf hin**, dass der Termin unrealistisch war.", "Она указала на то, что срок был нереалистичным."),
            ("Er **argumentierte**, dass wir warten sollten.", "Он утверждал, что нам стоит подождать."),
            ("Sie **erklärten**, dass die Änderung vorübergehend war.", "Они объяснили, что изменение временное."),
            ("Sie **wies darauf hin**, dass die Daten unvollständig waren.", "Она указала на то, что данные неполные."),
            ("Er **argumentierte**, dass die Kosten zu hoch waren.", "Он утверждал, что стоимость слишком высока."),
            ("Sie **wiesen darauf hin**, dass wir einen Schritt ausgelassen hatten.", "Они указали на то, что мы пропустили шаг."),
            ("Sie **erklärte**, dass die Verzögerung unvermeidbar war.", "Она объяснила, что задержка была неизбежна."),
            ("Er **wies darauf hin**, dass dies schon einmal passiert war.", "Он указал на то, что такое уже случалось."),
            ("Sie **argumentierten**, dass ein kleinerer Umfang sicherer war.", "Они утверждали, что меньший объём безопаснее."),
            ("Sie **wies darauf hin**, dass niemand die Aufgabe besaß.", "Она указала на то, что за задачу никто не отвечает."),
            ("Er **erklärte**, dass das Risiko gering war.", "Он объяснил, что риск невелик."),
            ("**Wies sie darauf hin**, dass sich der Plan geändert hatte?", "Она указала на то, что план изменился?"),
        ])),

    P("REP002", "REP", "Заявлять / предполагать / настаивать, что…",
      "claim, suggest, maintain — передача позиции с оттенком дистанции. claim часто намекает на сомнение, suggest — на мягкое предложение, maintain — на упорство. Тон решает всё.",
      L("claim / suggest / maintain that + clause",
        "They claimed that the system was secure.",
        "Они заявляли, что система безопасна.",
        [
            ("They **claimed that** the system was secure.", "Они заявляли, что система безопасна."),
            ("She **suggested that** we try a different approach.", "Она предположила, что нам стоит попробовать другой подход."),
            ("He **maintained that** he was right.", "Он настаивал на том, что был прав."),
            ("They **claimed that** the results were final.", "Они заявляли, что результаты окончательные."),
            ("She **suggested that** the meeting be postponed.", "Она предложила перенести встречу."),
            ("He **claimed that** he had not been informed.", "Он утверждал, что его не проинформировали."),
            ("They **maintained that** the data was accurate.", "Они настаивали на том, что данные точны."),
            ("She **claimed that** the cost would fall.", "Она заявляла, что стоимость снизится."),
            ("He **suggested that** we test it first.", "Он предложил сначала это протестировать."),
            ("They **claimed that** the delay was not their fault.", "Они утверждали, что задержка не их вина."),
            ("She **maintained that** the plan would work.", "Она настаивала на том, что план сработает."),
            ("Did they **claim that** the issue was resolved?", "Они заявляли, что проблема решена?"),
        ]),
      L("behaupten / nahelegen / beharren darauf, dass",
        "Sie behaupteten, dass das System sicher war.",
        "Они заявляли, что система безопасна.",
        [
            ("Sie **behaupteten**, dass das System sicher war.", "Они заявляли, что система безопасна."),
            ("Sie **legte nahe**, dass wir einen anderen Ansatz versuchen.", "Она предположила, что нам стоит попробовать другой подход."),
            ("Er **beharrte darauf**, dass er Recht hatte.", "Он настаивал на том, что был прав."),
            ("Sie **behaupteten**, dass die Ergebnisse endgültig waren.", "Они заявляли, что результаты окончательные."),
            ("Sie **schlug vor**, dass das Meeting verschoben wird.", "Она предложила перенести встречу."),
            ("Er **behauptete**, dass er nicht informiert worden war.", "Он утверждал, что его не проинформировали."),
            ("Sie **beharrten darauf**, dass die Daten korrekt waren.", "Они настаивали на том, что данные точны."),
            ("Sie **behauptete**, dass die Kosten sinken würden.", "Она заявляла, что стоимость снизится."),
            ("Er **legte nahe**, dass wir es zuerst testen.", "Он предложил сначала это протестировать."),
            ("Sie **behaupteten**, dass die Verzögerung nicht ihre Schuld war.", "Они утверждали, что задержка не их вина."),
            ("Sie **beharrte darauf**, dass der Plan funktionieren würde.", "Она настаивала на том, что план сработает."),
            ("**Behaupteten sie**, dass das Problem gelöst war?", "Они заявляли, что проблема решена?"),
        ])),

    P("REP003", "REP", "Признать / уступить / предупредить, что…",
      "acknowledge, concede, warn — передача позиции с уступкой или предостережением. Эти глаголы показывают зрелость: ты слышишь другую сторону и честно называешь риски.",
      L("acknowledge / concede / warn that + clause",
        "She acknowledged that the plan had flaws.",
        "Она признала, что у плана есть недостатки.",
        [
            ("She **acknowledged that** the plan had flaws.", "Она признала, что у плана есть недостатки."),
            ("He **conceded that** we had a point.", "Он признал, что в наших словах есть смысл."),
            ("They **warned that** the costs might rise.", "Они предупредили, что расходы могут вырасти."),
            ("She **acknowledged that** she had made a mistake.", "Она признала, что допустила ошибку."),
            ("He **conceded that** the task was harder than expected.", "Он признал, что задача оказалась сложнее, чем ожидалось."),
            ("They **warned that** the deadline might slip.", "Они предупредили, что срок может сорваться."),
            ("She **acknowledged that** more data was needed.", "Она признала, что нужно больше данных."),
            ("He **conceded that** the criticism was fair.", "Он признал, что критика была справедливой."),
            ("They **warned that** the system could fail.", "Они предупредили, что система может дать сбой."),
            ("She **acknowledged that** the team was under pressure.", "Она признала, что команда была под давлением."),
            ("He **conceded that** he had been wrong.", "Он признал, что был неправ."),
            ("Did they **warn that** the risk was high?", "Они предупредили, что риск высок?"),
        ]),
      L("einräumen / zugeben / warnen, dass",
        "Sie räumte ein, dass der Plan Schwächen hatte.",
        "Она признала, что у плана есть недостатки.",
        [
            ("Sie **räumte ein**, dass der Plan Schwächen hatte.", "Она признала, что у плана есть недостатки."),
            ("Er **gab zu**, dass wir einen Punkt hatten.", "Он признал, что в наших словах есть смысл."),
            ("Sie **warnten**, dass die Kosten steigen könnten.", "Они предупредили, что расходы могут вырасти."),
            ("Sie **räumte ein**, dass sie einen Fehler gemacht hatte.", "Она признала, что допустила ошибку."),
            ("Er **gab zu**, dass die Aufgabe schwerer war als erwartet.", "Он признал, что задача оказалась сложнее, чем ожидалось."),
            ("Sie **warnten**, dass der Termin verrutschen könnte.", "Они предупредили, что срок может сорваться."),
            ("Sie **räumte ein**, dass mehr Daten nötig waren.", "Она признала, что нужно больше данных."),
            ("Er **gab zu**, dass die Kritik berechtigt war.", "Он признал, что критика была справедливой."),
            ("Sie **warnten**, dass das System ausfallen könnte.", "Они предупредили, что система может дать сбой."),
            ("Sie **räumte ein**, dass das Team unter Druck stand.", "Она признала, что команда была под давлением."),
            ("Er **gab zu**, dass er sich geirrt hatte.", "Он признал, что был неправ."),
            ("**Warnten sie**, dass das Risiko hoch war?", "Они предупредили, что риск высок?"),
        ])),

    # ============================================================ EMP — Emphasis / inversion
    P("EMP001", "EMP", "Только после X я понял (инверсия)",
      "Only after/when меняет порядок слов: вспомогательный глагол идёт перед подлежащим. Это и есть C1-акцент — «только тогда я понял». В немецком после Erst nach X глагол стоит на втором месте.",
      L("Only after/when X did + subj + verb",
        "Only after the meeting did I realize how much work remained.",
        "Только после встречи я понял, сколько работы осталось.",
        [
            ("Only after the meeting **did I realize** how much work remained.", "Только после встречи я понял, сколько работы осталось."),
            ("Only when she apologized **did he finally calm** down.", "Только когда она извинилась, он наконец успокоился."),
            ("Only after losing the contract **did the company change** its strategy.", "Только потеряв контракт, компания изменила стратегию."),
            ("Only after I had read the report **did the problem become** clear.", "Только прочитав отчёт, я понял суть проблемы."),
            ("Only then **did we notice** the error in the data.", "Только тогда мы заметили ошибку в данных."),
            ("Only after a year abroad **did I feel** truly fluent.", "Только после года за границей я почувствовал, что говорю свободно."),
            ("Only when the deadline passed **did they take** it seriously.", "Только когда срок прошёл, они отнеслись к этому серьёзно."),
            ("Only in recent years **has this view changed**.", "Только в последние годы это мнение изменилось."),
            ("Only after asking twice **did she get** an answer.", "Только после двух повторов она получила ответ."),
            ("Only when you lose something **do you appreciate** it.", "Только потеряв что-то, ты начинаешь это ценить."),
            ("Only after the scandal broke **did he resign**.", "Только после того, как разразился скандал, он подал в отставку."),
            ("Only rarely **do we see** results like these.", "Лишь изредка мы видим такие результаты."),
        ]),
      L("Erst nach/als X wurde/war mir klar, dass …",
        "Erst nach dem Meeting wurde mir klar, wie viel Arbeit übrig war.",
        "Только после встречи я понял, сколько работы осталось.",
        [
            ("Erst nach dem Meeting **wurde mir klar**, wie viel Arbeit übrig war.", "Только после встречи я понял, сколько работы осталось."),
            ("Erst als sie sich entschuldigte, **beruhigte er sich** endlich.", "Только когда она извинилась, он наконец успокоился."),
            ("Erst nach dem Verlust des Auftrags **änderte die Firma** ihre Strategie.", "Только потеряв заказ, фирма изменила стратегию."),
            ("Erst nachdem ich den Bericht gelesen hatte, **wurde das Problem klar**.", "Только прочитав отчёт, я понял проблему."),
            ("Erst dann **bemerkten wir** den Fehler in den Daten.", "Только тогда мы заметили ошибку в данных."),
            ("Erst nach einem Jahr im Ausland **fühlte ich mich** wirklich sicher.", "Только после года за границей я почувствовал себя уверенно."),
            ("Erst als die Frist abgelaufen war, **nahmen sie es** ernst.", "Только когда срок истёк, они отнеслись к этому серьёзно."),
            ("Erst in den letzten Jahren **hat sich** diese Ansicht geändert.", "Только в последние годы это мнение изменилось."),
            ("Erst nach zwei Nachfragen **bekam sie** eine Antwort.", "Только после двух повторных запросов она получила ответ."),
            ("Erst wenn man etwas verliert, **schätzt man es**.", "Только потеряв что-то, начинаешь это ценить."),
            ("Erst nachdem der Skandal bekannt wurde, **trat er zurück**.", "Только после того, как скандал стал известен, он подал в отставку."),
            ("Erst nach langem Zögern **stimmte er** schließlich zu.", "Только после долгих колебаний он наконец согласился."),
        ])),

    P("EMP002", "EMP", "Had it not been for X / Ohne X wäre",
      "Инверсия условия без if: Had it not been for… — «если бы не…». Очень письменный и речевой C1-оборот. В немецком то же даёт Ohne + Konj II: Ohne X wäre Y nicht passiert.",
      L("Had it not been for X, Y would not have + pp",
        "Had it not been for her quick thinking, the launch would have failed.",
        "Если бы не её быстрая реакция, запуск провалился бы.",
        [
            ("**Had it not been for** her quick thinking, the launch would have failed.", "Если бы не её быстрая реакция, запуск бы провалился."),
            ("**Had it not been for** the warning, we would have lost everything.", "Если бы не предупреждение, мы бы всё потеряли."),
            ("**Had it not been for** his support, I would have given up.", "Если бы не его поддержка, я бы сдался."),
            ("**Had it not been for** the traffic, we would have arrived on time.", "Если бы не пробки, мы бы приехали вовремя."),
            ("**Had it not been for** their mistake, the project would have succeeded.", "Если бы не их ошибка, проект бы удался."),
            ("**Had it not been for** the rain, the event would have been outdoors.", "Если бы не дождь, мероприятие прошло бы на улице."),
            ("**Had it not been for** one missing document, the deal would have closed.", "Если бы не один недостающий документ, сделка бы состоялась."),
            ("**Had it not been for** your advice, I would have made a serious error.", "Если бы не твой совет, я бы допустил серьёзную ошибку."),
            ("**Had it not been for** the delay, they would have won the contract.", "Если бы не задержка, они бы выиграли контракт."),
            ("**Had it not been for** luck, none of this would have happened.", "Если бы не удача, ничего этого бы не случилось."),
            ("**Had it not been for** the new evidence, the case would have been closed.", "Если бы не новые доказательства, дело было бы закрыто."),
            ("Would you have stayed **had it not been for** the team?", "Ты бы остался, если бы не команда?"),
        ]),
      L("Ohne X wäre Y nicht + pp (Konj II)",
        "Ohne ihre schnelle Reaktion wäre der Start gescheitert.",
        "Если бы не её быстрая реакция, запуск бы провалился.",
        [
            ("**Ohne** ihre schnelle Reaktion **wäre** der Start gescheitert.", "Если бы не её быстрая реакция, запуск бы провалился."),
            ("**Ohne** die Warnung **hätten wir** alles verloren.", "Если бы не предупреждение, мы бы всё потеряли."),
            ("**Ohne** seine Unterstützung **hätte ich** aufgegeben.", "Если бы не его поддержка, я бы сдался."),
            ("**Ohne** den Stau **wären wir** pünktlich angekommen.", "Если бы не пробку, мы бы приехали вовремя."),
            ("**Ohne** ihren Fehler **wäre** das Projekt geglückt.", "Если бы не их ошибку, проект бы удался."),
            ("**Ohne** den Regen **hätte** die Veranstaltung draußen stattgefunden.", "Если бы не дождь, мероприятие прошло бы на улице."),
            ("**Ohne** das fehlende Dokument **wäre** der Vertrag zustande gekommen.", "Если бы не недостающий документ, договор состоялся бы."),
            ("**Ohne** deinen Rat **hätte ich** einen ernsten Fehler gemacht.", "Если бы не твой совет, я бы допустил серьёзную ошибку."),
            ("**Ohne** die Verzögerung **hätten sie** den Auftrag gewonnen.", "Если бы не задержку, они бы выиграли заказ."),
            ("**Ohne** Glück **wäre** nichts davon passiert.", "Если бы не удача, ничего этого бы не случилось."),
            ("**Ohne** die neuen Beweise **wäre** der Fall abgeschlossen worden.", "Если бы не новые доказательства, дело было бы закрыто."),
            ("**Wärst du ohne** das Team geblieben?", "Ты бы остался, если бы не команда?"),
        ])),

    P("EMP003", "EMP", "What surprised me was… (расщеплённое предложение)",
      "Cleft sentence: выносим главное в начало — What surprised me most was… По-немецки: Was mich überrascht hat, war… Глагол в was-части уходит в конец.",
      L("What + verb + me (most) was …",
        "What surprised me most was how quickly they adapted.",
        "Что удивило меня больше всего — как быстро они адаптировались.",
        [
            ("**What surprised me most was** how quickly they adapted.", "Что удивило меня больше всего — как быстро они адаптировались."),
            ("**What annoyed me was** the constant noise.", "Что раздражало меня — постоянный шум."),
            ("**What impressed her was** his honesty.", "Что впечатлило её — его честность."),
            ("**What worried the team was** the lack of time.", "Что беспокоило команду — нехватка времени."),
            ("**What surprised us was** that nobody complained.", "Что удивило нас — что никто не жаловался."),
            ("**What I find difficult is** staying focused.", "Что я считаю сложным — оставаться сосредоточенным."),
            ("**What shocked everyone was** the sudden announcement.", "Что шокировало всех — внезапное объявление."),
            ("**What matters most is** consistency.", "Что важнее всего — последовательность."),
            ("**What disappointed me was** the quality of the work.", "Что разочаровало меня — качество работы."),
            ("**What she needed was** a little more time.", "Что ей было нужно — ещё немного времени."),
            ("**What made the difference was** careful planning.", "Что решило исход — тщательное планирование."),
            ("**What surprised me wasn't** the cost but the delay.", "Что удивило меня — не цена, а задержка."),
        ]),
      L("Was mich (am meisten) überrascht hat, war …",
        "Was mich am meisten überrascht hat, war, wie schnell sie sich angepasst haben.",
        "Что удивило меня больше всего — как быстро они адаптировались.",
        [
            ("**Was mich am meisten überrascht hat, war**, wie schnell sie sich angepasst haben.", "Что удивило меня больше всего — как быстро они адаптировались."),
            ("**Was mich genervt hat, war** der ständige Lärm.", "Что раздражало меня — постоянный шум."),
            ("**Was sie beeindruckt hat, war** seine Ehrlichkeit.", "Что впечатлило её — его честность."),
            ("**Was das Team beunruhigt hat, war** der Zeitmangel.", "Что беспокоило команду — нехватка времени."),
            ("**Was uns überrascht hat, war**, dass sich niemand beschwert hat.", "Что удивило нас — что никто не жаловался."),
            ("**Was ich schwierig finde, ist**, konzentriert zu bleiben.", "Что я считаю сложным — оставаться сосредоточенным."),
            ("**Was alle schockiert hat, war** die plötzliche Ankündigung.", "Что шокировало всех — внезапное объявление."),
            ("**Was am wichtigsten ist, ist** Beständigkeit.", "Что важнее всего — постоянство."),
            ("**Was mich enttäuscht hat, war** die Qualität der Arbeit.", "Что разочаровало меня — качество работы."),
            ("**Was sie gebraucht hat, war** ein bisschen mehr Zeit.", "Что ей было нужно — ещё немного времени."),
            ("**Was den Unterschied gemacht hat, war** die sorgfältige Planung.", "Что решило исход — тщательное планирование."),
            ("**Was mich überrascht hat, war** nicht der Preis, sondern die Verzögerung.", "Что удивило меня — не цена, а задержка."),
        ])),

    # ============================================================ HED — Hedging / stance
    P("HED001", "HED", "It could be argued that… (осторожная позиция)",
      "C1 говорит осторожно, не категорично. It could be argued that… — «можно утверждать, что…». По-немецки: Man könnte argumentieren, dass…",
      L("It could be argued that …",
        "It could be argued that the policy has done more harm than good.",
        "Можно утверждать, что эта политика принесла больше вреда, чем пользы.",
        [
            ("**It could be argued that** the policy has done more harm than good.", "Можно утверждать, что политика принесла больше вреда, чем пользы."),
            ("**It could be argued that** remote work increases productivity.", "Можно утверждать, что удалённая работа повышает продуктивность."),
            ("**It could be argued that** the cost outweighs the benefit.", "Можно утверждать, что затраты перевешивают выгоду."),
            ("**It could be argued that** we acted too quickly.", "Можно утверждать, что мы действовали слишком быстро."),
            ("**It could be argued that** the data is incomplete.", "Можно утверждать, что данные неполны."),
            ("**It could be argued that** competition drives innovation.", "Можно утверждать, что конкуренция стимулирует инновации."),
            ("**It could be argued that** the decision was justified.", "Можно утверждать, что решение было оправдано."),
            ("**It could be argued that** the opposite is true.", "Можно утверждать, что верно обратное."),
            ("**It could be argued that** education should be free.", "Можно утверждать, что образование должно быть бесплатным."),
            ("**It could be argued that** the plan needs revision.", "Можно утверждать, что план требует пересмотра."),
            ("**It could be argued that** nobody is entirely blameless here.", "Можно утверждать, что здесь никто полностью не безупречен."),
            ("**Could it be argued that** the risk was underestimated?", "Можно ли утверждать, что риск был недооценён?"),
        ]),
      L("Man könnte argumentieren, dass …",
        "Man könnte argumentieren, dass die Politik mehr geschadet als genutzt hat.",
        "Можно утверждать, что эта политика принесла больше вреда, чем пользы.",
        [
            ("**Man könnte argumentieren, dass** die Politik mehr geschadet als genutzt hat.", "Можно утверждать, что политика принесла больше вреда, чем пользы."),
            ("**Man könnte argumentieren, dass** Heimarbeit die Produktivität erhöht.", "Можно утверждать, что удалённая работа повышает продуктивность."),
            ("**Man könnte argumentieren, dass** die Kosten den Nutzen überwiegen.", "Можно утверждать, что затраты перевешивают пользу."),
            ("**Man könnte argumentieren, dass** wir zu schnell gehandelt haben.", "Можно утверждать, что мы действовали слишком быстро."),
            ("**Man könnte argumentieren, dass** die Daten unvollständig sind.", "Можно утверждать, что данные неполны."),
            ("**Man könnte argumentieren, dass** Wettbewerb Innovation fördert.", "Можно утверждать, что конкуренция стимулирует инновации."),
            ("**Man könnte argumentieren, dass** die Entscheidung gerechtfertigt war.", "Можно утверждать, что решение было оправдано."),
            ("**Man könnte argumentieren, dass** das Gegenteil zutrifft.", "Можно утверждать, что верно обратное."),
            ("**Man könnte argumentieren, dass** Bildung kostenlos sein sollte.", "Можно утверждать, что образование должно быть бесплатным."),
            ("**Man könnte argumentieren, dass** der Plan überarbeitet werden muss.", "Можно утверждать, что план нужно пересмотреть."),
            ("**Man könnte argumentieren, dass** hier niemand völlig unschuldig ist.", "Можно утверждать, что здесь никто полностью не безупречен."),
            ("**Könnte man argumentieren, dass** das Risiko unterschätzt wurde?", "Можно ли утверждать, что риск был недооценён?"),
        ])),

    P("HED002", "HED", "It remains to be seen whether… (пока неясно)",
      "Ещё один осторожный C1-оборот: It remains to be seen whether… — «ещё предстоит выяснить». По-немецки: Es bleibt abzuwarten, ob…",
      L("It remains to be seen whether …",
        "It remains to be seen whether the reform will work.",
        "Ещё предстоит выяснить, сработает ли реформа.",
        [
            ("**It remains to be seen whether** the reform will work.", "Ещё предстоит выяснить, сработает ли реформа."),
            ("**It remains to be seen whether** they will accept the offer.", "Ещё предстоит выяснить, примут ли они предложение."),
            ("**It remains to be seen whether** the costs can be recovered.", "Ещё предстоит выяснить, удастся ли возместить расходы."),
            ("**It remains to be seen whether** the weather will improve.", "Ещё предстоит выяснить, улучшится ли погода."),
            ("**It remains to be seen whether** he will keep his promise.", "Ещё предстоит выяснить, сдержит ли он обещание."),
            ("**It remains to be seen whether** the new law will help.", "Ещё предстоит выяснить, поможет ли новый закон."),
            ("**It remains to be seen whether** the trend will continue.", "Ещё предстоит выяснить, продолжится ли тенденция."),
            ("**It remains to be seen whether** we can meet the deadline.", "Ещё предстоит выяснить, успеем ли мы к сроку."),
            ("**It remains to be seen whether** the treatment is effective.", "Ещё предстоит выяснить, эффективно ли лечение."),
            ("**It remains to be seen whether** she will return.", "Ещё предстоит выяснить, вернётся ли она."),
            ("**It remains to be seen whether** the market will stabilize.", "Ещё предстоит выяснить, стабилизируется ли рынок."),
            ("**It remains to be seen whether** any of this was worth it.", "Ещё предстоит выяснить, стоило ли всё это того."),
        ]),
      L("Es bleibt abzuwarten, ob …",
        "Es bleibt abzuwarten, ob die Reform funktionieren wird.",
        "Ещё предстоит выяснить, сработает ли реформа.",
        [
            ("**Es bleibt abzuwarten, ob** die Reform funktionieren wird.", "Ещё предстоит выяснить, сработает ли реформа."),
            ("**Es bleibt abzuwarten, ob** sie das Angebot annehmen werden.", "Ещё предстоит выяснить, примут ли они предложение."),
            ("**Es bleibt abzuwarten, ob** sich die Kosten decken lassen.", "Ещё предстоит выяснить, удастся ли покрыть расходы."),
            ("**Es bleibt abzuwarten, ob** das Wetter besser wird.", "Ещё предстоит выяснить, улучшится ли погода."),
            ("**Es bleibt abzuwarten, ob** er sein Versprechen hält.", "Ещё предстоит выяснить, сдержит ли он обещание."),
            ("**Es bleibt abzuwarten, ob** das neue Gesetz helfen wird.", "Ещё предстоит выяснить, поможет ли новый закон."),
            ("**Es bleibt abzuwarten, ob** sich der Trend fortsetzt.", "Ещё предстоит выяснить, продолжится ли тенденция."),
            ("**Es bleibt abzuwarten, ob** wir den Termin einhalten können.", "Ещё предстоит выяснить, успеем ли мы к сроку."),
            ("**Es bleibt abzuwarten, ob** die Behandlung wirkt.", "Ещё предстоит выяснить, действует ли лечение."),
            ("**Es bleibt abzuwarten, ob** sie zurückkommt.", "Ещё предстоит выяснить, вернётся ли она."),
            ("**Es bleibt abzuwarten, ob** sich der Markt stabilisiert.", "Ещё предстоит выяснить, стабилизируется ли рынок."),
            ("**Es bleibt abzuwarten, ob** sich all das gelohnt hat.", "Ещё предстоит выяснить, стоило ли всё это того."),
        ])),

    P("HED003", "HED", "There is (some) evidence that… (ссылка на доказательства)",
      "C1 опирается на доказательства, а не на голословные утверждения: There is growing/strong/little evidence that… По-немецки: Es gibt Hinweise darauf, dass…",
      L("There is (some/growing/little) evidence that …",
        "There is growing evidence that sleep affects memory.",
        "Есть всё больше доказательств того, что сон влияет на память.",
        [
            ("**There is growing evidence that** sleep affects memory.", "Есть всё больше доказательств того, что сон влияет на память."),
            ("**There is some evidence that** the method works.", "Есть некоторые доказательства того, что метод работает."),
            ("**There is little evidence that** the policy helped.", "Есть мало доказательств того, что политика помогла."),
            ("**There is strong evidence that** exercise improves mood.", "Есть убедительные доказательства того, что спорт улучшает настроение."),
            ("**There is no evidence that** he was involved.", "Нет доказательств того, что он был причастен."),
            ("**There is mounting evidence that** the climate is changing.", "Есть всё больше доказательств того, что климат меняется."),
            ("**There is clear evidence that** demand is falling.", "Есть явные доказательства того, что спрос падает."),
            ("**There is emerging evidence that** the drug is safe.", "Появляются доказательства того, что препарат безопасен."),
            ("**There is limited evidence that** the plan will succeed.", "Есть ограниченные доказательства того, что план сработает."),
            ("**There is considerable evidence that** prices are rising.", "Есть значительные доказательства того, что цены растут."),
            ("**There is scant evidence that** the change was necessary.", "Есть скудные доказательства того, что изменение было необходимо."),
            ("**Is there any evidence that** the claim is true?", "Есть ли какие-либо доказательства того, что утверждение верно?"),
        ]),
      L("Es gibt (einige/wenige) Hinweise darauf, dass …",
        "Es gibt immer mehr Hinweise darauf, dass Schlaf das Gedächtnis beeinflusst.",
        "Есть всё больше доказательств того, что сон влияет на память.",
        [
            ("**Es gibt immer mehr Hinweise darauf, dass** Schlaf das Gedächtnis beeinflusst.", "Есть всё больше доказательств того, что сон влияет на память."),
            ("**Es gibt einige Hinweise darauf, dass** die Methode funktioniert.", "Есть некоторые доказательства того, что метод работает."),
            ("**Es gibt wenige Hinweise darauf, dass** die Politik geholfen hat.", "Есть мало доказательств того, что политика помогла."),
            ("**Es gibt deutliche Hinweise darauf, dass** Sport die Stimmung verbessert.", "Есть явные доказательства того, что спорт улучшает настроение."),
            ("**Es gibt keine Hinweise darauf, dass** er beteiligt war.", "Нет доказательств того, что он был причастен."),
            ("**Es gibt zunehmend Hinweise darauf, dass** sich das Klima verändert.", "Есть всё больше доказательств того, что климат меняется."),
            ("**Es gibt klare Hinweise darauf, dass** die Nachfrage sinkt.", "Есть явные доказательства того, что спрос падает."),
            ("**Es gibt erste Hinweise darauf, dass** das Medikament sicher ist.", "Есть первые доказательства того, что препарат безопасен."),
            ("**Es gibt begrenzte Hinweise darauf, dass** der Plan gelingen wird.", "Есть ограниченные доказательства того, что план сработает."),
            ("**Es gibt erhebliche Hinweise darauf, dass** die Preise steigen.", "Есть значительные доказательства того, что цены растут."),
            ("**Es gibt kaum Hinweise darauf, dass** die Änderung nötig war.", "Есть скудные доказательства того, что изменение было необходимо."),
            ("**Gibt es Hinweise darauf, dass** die Behauptung stimmt?", "Есть ли доказательства того, что утверждение верно?"),
        ])),

    # ============================================================ CHNK — Conversational chunks / discourse
    P("CHNK001", "CHNK", "That being said / Trotzdem (уступка + контраст)",
      "Разговорный C1-связующий оборот: признаём, потом противопоставляем. That being said, … По-немецки: Trotzdem / Dennoch… После Dennoch — инверсия.",
      L("That being said, …",
        "The work is hard. That being said, it's worth it.",
        "Работа тяжёлая. При этом она того стоит.",
        [
            ("The work is hard. **That being said**, it's worth it.", "Работа тяжёлая. При этом она того стоит."),
            ("The price is high. **That being said**, the quality is excellent.", "Цена высокая. При этом качество отличное."),
            ("I disagree. **That being said**, I see your point.", "Я не согласен. При этом я понимаю твою точку зрения."),
            ("The plan is risky. **That being said**, we have few alternatives.", "План рискованный. При этом у нас мало альтернатив."),
            ("It rained all week. **That being said**, we enjoyed the trip.", "Всю неделю шёл дождь. При этом нам понравилась поездка."),
            ("The report is long. **That being said**, it's very thorough.", "Отчёт длинный. При этом он очень подробный."),
            ("He's inexperienced. **That being said**, he learns fast.", "У него мало опыта. При этом он быстро учится."),
            ("The meeting dragged on. **That being said**, we made progress.", "Встреча затянулась. При этом мы добились прогресса."),
            ("The software has bugs. **That being said**, it's improving.", "У программы есть ошибки. При этом она совершенствуется."),
            ("The exam was tough. **That being said**, most students passed.", "Экзамен был сложным. При этом большинство студентов сдали."),
            ("It's an old building. **That being said**, it has character.", "Это старое здание. При этом у него есть характер."),
            ("The deadline is tight. **That being said**, we can manage it.", "Срок сжатый. При этом мы справимся."),
        ]),
      L("Trotzdem / Dennoch, …",
        "Die Arbeit ist hart. Trotzdem lohnt sie sich.",
        "Работа тяжёлая. При этом она того стоит.",
        [
            ("Die Arbeit ist hart. **Trotzdem** lohnt sie sich.", "Работа тяжёлая. При этом она того стоит."),
            ("Der Preis ist hoch. **Dennoch ist** die Qualität ausgezeichnet.", "Цена высокая. При этом качество отличное."),
            ("Ich bin anderer Meinung. **Trotzdem** verstehe ich deinen Punkt.", "Я другого мнения. При этом я понимаю твою точку зрения."),
            ("Der Plan ist riskant. **Trotzdem** haben wir kaum Alternativen.", "План рискованный. При этом у нас почти нет альтернатив."),
            ("Es hat die ganze Woche geregnet. **Trotzdem** hat uns die Reise gefallen.", "Всю неделю шёл дождь. При этом нам понравилась поездка."),
            ("Der Bericht ist lang. **Dennoch ist** er sehr gründlich.", "Отчёт длинный. При этом он очень подробный."),
            ("Er ist unerfahren. **Trotzdem** lernt er schnell.", "У него мало опыта. При этом он быстро учится."),
            ("Das Meeting hat sich hingezogen. **Trotzdem** haben wir Fortschritte gemacht.", "Встреча затянулась. При этом мы добились прогресса."),
            ("Die Software hat Fehler. **Dennoch wird** sie besser.", "У программы есть ошибки. При этом она становится лучше."),
            ("Die Prüfung war schwer. **Trotzdem** haben die meisten bestanden.", "Экзамен был сложным. При этом большинство сдало."),
            ("Es ist ein altes Gebäude. **Trotzdem** hat es Charakter.", "Это старое здание. При этом у него есть характер."),
            ("Der Termin ist knapp. **Trotzdem** schaffen wir es.", "Срок сжатый. При этом мы справимся."),
        ])),

    P("CHNK002", "CHNK", "To be fair / Fairerweise (будем справедливы)",
      "To be fair, … — «честно говоря / по справедливости». Смягчает критику и звучит естественно. По-немецки: Fairerweise muss man sagen, dass…",
      L("To be fair, …",
        "To be fair, she had very little time to prepare.",
        "Честно говоря, у неё было очень мало времени на подготовку.",
        [
            ("**To be fair**, she had very little time to prepare.", "Честно говоря, у неё было мало времени на подготовку."),
            ("**To be fair**, he did warn us about the risks.", "Честно говоря, он предупреждал нас о рисках."),
            ("**To be fair**, the team worked incredibly hard.", "Честно говоря, команда работала очень усердно."),
            ("**To be fair**, it was a difficult situation for everyone.", "Честно говоря, это была сложная ситуация для всех."),
            ("**To be fair**, the product is good value for money.", "Честно говоря, продукт стоит своих денег."),
            ("**To be fair**, nobody could have predicted this.", "Честно говоря, никто не мог этого предсказать."),
            ("**To be fair**, they apologized immediately.", "Честно говоря, они сразу извинились."),
            ("**To be fair**, the criticism was partly justified.", "Честно говоря, критика была отчасти справедлива."),
            ("**To be fair**, we also made mistakes.", "Честно говоря, мы тоже допустили ошибки."),
            ("**To be fair**, the weather ruined most of the plans.", "Честно говоря, погода испортила большинство планов."),
            ("**To be fair**, he's new to the job.", "Честно говоря, он новичок в этой работе."),
            ("**To be fair**, haven't we all done the same?", "Честно говоря, разве мы все не делали так же?"),
        ]),
      L("Fairerweise muss man sagen, dass …",
        "Fairerweise muss man sagen, dass sie sehr wenig Zeit hatte.",
        "Честно говоря, у неё было очень мало времени.",
        [
            ("**Fairerweise muss man sagen, dass** sie sehr wenig Zeit hatte.", "Честно говоря, у неё было мало времени."),
            ("**Fairerweise muss man sagen, dass** er uns vor den Risiken gewarnt hat.", "Честно говоря, он предупреждал нас о рисках."),
            ("**Fairerweise muss man sagen, dass** das Team sehr hart gearbeitet hat.", "Честно говоря, команда работала очень усердно."),
            ("**Fairerweise muss man sagen, dass** es für alle eine schwierige Situation war.", "Честно говоря, это была сложная ситуация для всех."),
            ("**Fairerweise muss man sagen, dass** das Produkt sein Geld wert ist.", "Честно говоря, продукт стоит своих денег."),
            ("**Fairerweise muss man sagen, dass** das niemand vorhersehen konnte.", "Честно говоря, никто не мог этого предсказать."),
            ("**Fairerweise muss man sagen, dass** sie sich sofort entschuldigt haben.", "Честно говоря, они сразу извинились."),
            ("**Fairerweise muss man sagen, dass** die Kritik teilweise berechtigt war.", "Честно говоря, критика была отчасти справедлива."),
            ("**Fairerweise muss man sagen, dass** auch wir Fehler gemacht haben.", "Честно говоря, мы тоже допустили ошибки."),
            ("**Fairerweise muss man sagen, dass** das Wetter die meisten Pläne ruiniert hat.", "Честно говоря, погода испортила большинство планов."),
            ("**Fairerweise muss man sagen, dass** er neu im Job ist.", "Честно говоря, он новичок в этой работе."),
            ("**Fairerweise muss man sagen, dass** wir alle schon Ähnliches getan haben.", "Честно говоря, мы все уже делали нечто подобное."),
        ])),

    P("CHNK003", "CHNK", "At the end of the day / The thing is (подводя итог)",
      "Два живых разговорных оборота: At the end of the day… — «в конечном счёте», и The thing is… — «дело в том, что». По-немецки: Letztendlich… / Die Sache ist…",
      L("At the end of the day, … / The thing is, …",
        "At the end of the day, what matters is trust.",
        "В конечном счёте важно доверие.",
        [
            ("**At the end of the day**, what matters is trust.", "В конечном счёте важно доверие."),
            ("**The thing is**, we simply don't have the budget.", "Дело в том, что у нас просто нет бюджета."),
            ("**At the end of the day**, results speak louder than words.", "В конечном счёте результаты говорят громче слов."),
            ("**The thing is**, nobody told me about the change.", "Дело в том, что мне никто не сказал об изменении."),
            ("**At the end of the day**, it's your decision to make.", "В конечном счёте это твоё решение."),
            ("**The thing is**, I've already tried that approach.", "Дело в том, что я уже пробовал этот подход."),
            ("**At the end of the day**, we all want the same thing.", "В конечном счёте мы все хотим одного и того же."),
            ("**The thing is**, the timing couldn't be worse.", "Дело в том, что время не могло быть хуже."),
            ("**At the end of the day**, quality beats quantity.", "В конечном счёте качество побеждает количество."),
            ("**The thing is**, she never actually agreed to it.", "Дело в том, что она так и не согласилась."),
            ("**At the end of the day**, money isn't everything.", "В конечном счёте деньги — не всё."),
            ("**At the end of the day**, isn't honesty what counts?", "В конечном счёте разве не честность главное?"),
        ]),
      L("Letztendlich, … / Die Sache ist, …",
        "Letztendlich zählt das Vertrauen.",
        "В конечном счёте важно доверие.",
        [
            ("**Letztendlich** zählt das Vertrauen.", "В конечном счёте важно доверие."),
            ("**Die Sache ist**, wir haben einfach kein Budget.", "Дело в том, что у нас просто нет бюджета."),
            ("**Letztendlich** sprechen Ergebnisse lauter als Worte.", "В конечном счёте результаты говорят громче слов."),
            ("**Die Sache ist**, niemand hat mir von der Änderung erzählt.", "Дело в том, что мне никто не сказал об изменении."),
            ("**Letztendlich** ist es deine Entscheidung.", "В конечном счёте это твоё решение."),
            ("**Die Sache ist**, ich habe diesen Ansatz schon versucht.", "Дело в том, что я уже пробовал этот подход."),
            ("**Letztendlich** wollen wir alle dasselbe.", "В конечном счёте мы все хотим одного и того же."),
            ("**Die Sache ist**, das Timing könnte nicht schlechter sein.", "Дело в том, что время не могло быть хуже."),
            ("**Letztendlich** schlägt Qualität die Quantität.", "В конечном счёте качество побеждает количество."),
            ("**Die Sache ist**, sie hat nie wirklich zugestimmt.", "Дело в том, что она так и не согласилась."),
            ("**Letztendlich** ist Geld nicht alles.", "В конечном счёте деньги — не всё."),
            ("**Letztendlich** zählt doch die Ehrlichkeit, oder?", "В конечном счёте главное — честность, не так ли?"),
        ])),

    # ============================================================ ABS — Abstract / higher-level language
    P("ABS001", "ABS", "This raises a broader question about… (выход на общее)",
      "C1 умеет обобщать: This raises a broader question about… — «это ставит более общий вопрос». По-немецки: Das wirft die Frage auf… (aufwerfen — отделяемый глагол).",
      L("This raises a broader question about …",
        "This raises a broader question about how we value privacy.",
        "Это ставит более общий вопрос о том, как мы ценим приватность.",
        [
            ("**This raises a broader question about** how we value privacy.", "Это ставит более общий вопрос о том, как мы ценим приватность."),
            ("**This raises a broader question about** the role of technology.", "Это ставит более общий вопрос о роли технологий."),
            ("**This raises a broader question about** who should be responsible.", "Это ставит более общий вопрос о том, кто должен нести ответственность."),
            ("**This raises a broader question about** the meaning of progress.", "Это ставит более общий вопрос о смысле прогресса."),
            ("**This raises a broader question about** fairness in hiring.", "Это ставит более общий вопрос о справедливости при найме."),
            ("**This raises a broader question about** how we measure success.", "Это ставит более общий вопрос о том, как мы измеряем успех."),
            ("**This raises a broader question about** the limits of free speech.", "Это ставит более общий вопрос о границах свободы слова."),
            ("**This raises a broader question about** education and inequality.", "Это ставит более общий вопрос об образовании и неравенстве."),
            ("**This raises a broader question about** what we owe each other.", "Это ставит более общий вопрос о том, что мы должны друг другу."),
            ("**This raises a broader question about** the future of work.", "Это ставит более общий вопрос о будущем работы."),
            ("**This raises a broader question about** trust in institutions.", "Это ставит более общий вопрос о доверии к институтам."),
            ("**Doesn't this raise a broader question about** our priorities?", "Разве это не ставит более общий вопрос о наших приоритетах?"),
        ]),
      L("Das wirft die grundsätzlichere Frage auf, …",
        "Das wirft die grundsätzlichere Frage auf, wie wir Privatsphäre bewerten.",
        "Это ставит более общий вопрос о том, как мы ценим приватность.",
        [
            ("**Das wirft die grundsätzlichere Frage auf**, wie wir Privatsphäre bewerten.", "Это ставит более общий вопрос о том, как мы ценим приватность."),
            ("**Das wirft die grundsätzlichere Frage** nach der Rolle der Technologie **auf**.", "Это ставит более общий вопрос о роли технологий."),
            ("**Das wirft die grundsätzlichere Frage auf**, wer verantwortlich sein sollte.", "Это ставит более общий вопрос о том, кто должен быть ответственным."),
            ("**Das wirft die grundsätzlichere Frage** nach dem Sinn des Fortschritts **auf**.", "Это ставит более общий вопрос о смысле прогресса."),
            ("**Das wirft die grundsätzlichere Frage** nach Fairness bei der Einstellung **auf**.", "Это ставит более общий вопрос о справедливости при найме."),
            ("**Das wirft die grundsätzlichere Frage auf**, wie wir Erfolg messen.", "Это ставит более общий вопрос о том, как мы измеряем успех."),
            ("**Das wirft die grundsätzlichere Frage** nach den Grenzen der Meinungsfreiheit **auf**.", "Это ставит более общий вопрос о границах свободы слова."),
            ("**Das wirft die grundsätzlichere Frage** nach Bildung und Ungleichheit **auf**.", "Это ставит более общий вопрос об образовании и неравенстве."),
            ("**Das wirft die grundsätzlichere Frage auf**, was wir einander schulden.", "Это ставит более общий вопрос о том, что мы должны друг другу."),
            ("**Das wirft die grundsätzlichere Frage** nach der Zukunft der Arbeit **auf**.", "Это ставит более общий вопрос о будущем работы."),
            ("**Das wirft die grundsätzlichere Frage** nach dem Vertrauen in Institutionen **auf**.", "Это ставит более общий вопрос о доверии к институтам."),
            ("**Wirft das nicht die grundsätzlichere Frage** nach unseren Prioritäten **auf**?", "Разве это не ставит более общий вопрос о наших приоритетах?"),
        ])),

    P("ABS002", "ABS", "The underlying principle is… (суть принципа)",
      "Формулируем принцип абстрактно: The underlying principle is that… По-немецки: Das zugrunde liegende Prinzip ist, dass…",
      L("The underlying principle is …",
        "The underlying principle is that everyone deserves a fair chance.",
        "Основной принцип в том, что каждый заслуживает честного шанса.",
        [
            ("**The underlying principle is** that everyone deserves a fair chance.", "Основной принцип в том, что каждый заслуживает честного шанса."),
            ("**The underlying principle is** simple: less is more.", "Основной принцип прост: меньше — значит больше."),
            ("**The underlying principle is** that prevention beats cure.", "Основной принцип в том, что профилактика лучше лечения."),
            ("**The underlying principle is** that data should drive decisions.", "Основной принцип в том, что решения должны опираться на данные."),
            ("**The underlying principle is** that trust takes time to build.", "Основной принцип в том, что доверие строится со временем."),
            ("**The underlying principle is** that clarity comes before speed.", "Основной принцип в том, что ясность важнее скорости."),
            ("**The underlying principle is** that no one is above the law.", "Основной принцип в том, что никто не выше закона."),
            ("**The underlying principle is** that feedback fuels growth.", "Основной принцип в том, что обратная связь питает рост."),
            ("**The underlying principle is** that simplicity wins.", "Основной принцип в том, что простота побеждает."),
            ("**The underlying principle is** that we learn by doing.", "Основной принцип в том, что мы учимся на практике."),
            ("**The underlying principle is** that small steps add up.", "Основной принцип в том, что маленькие шаги накапливаются."),
            ("**Is the underlying principle** really that hard to grasp?", "Неужели основной принцип так трудно понять?"),
        ]),
      L("Das zugrunde liegende Prinzip ist, dass …",
        "Das zugrunde liegende Prinzip ist, dass jeder eine faire Chance verdient.",
        "Основной принцип в том, что каждый заслуживает честного шанса.",
        [
            ("**Das zugrunde liegende Prinzip ist, dass** jeder eine faire Chance verdient.", "Основной принцип в том, что каждый заслуживает честного шанса."),
            ("**Das zugrunde liegende Prinzip ist** einfach: Weniger ist mehr.", "Основной принцип прост: меньше — значит больше."),
            ("**Das zugrunde liegende Prinzip ist, dass** Vorsorge besser ist als Nachsorge.", "Основной принцип в том, что профилактика лучше лечения."),
            ("**Das zugrunde liegende Prinzip ist, dass** Entscheidungen auf Daten beruhen sollten.", "Основной принцип в том, что решения должны опираться на данные."),
            ("**Das zugrunde liegende Prinzip ist, dass** Vertrauen Zeit braucht.", "Основной принцип в том, что доверию нужно время."),
            ("**Das zugrunde liegende Prinzip ist, dass** Klarheit vor Tempo kommt.", "Основной принцип в том, что ясность важнее скорости."),
            ("**Das zugrunde liegende Prinzip ist, dass** niemand über dem Gesetz steht.", "Основной принцип в том, что никто не выше закона."),
            ("**Das zugrunde liegende Prinzip ist, dass** Feedback das Wachstum fördert.", "Основной принцип в том, что обратная связь питает рост."),
            ("**Das zugrunde liegende Prinzip ist, dass** Einfachheit gewinnt.", "Основной принцип в том, что простота побеждает."),
            ("**Das zugrunde liegende Prinzip ist, dass** wir durch Tun lernen.", "Основной принцип в том, что мы учимся на практике."),
            ("**Das zugrunde liegende Prinzip ist, dass** sich kleine Schritte summieren.", "Основной принцип в том, что маленькие шаги накапливаются."),
            ("**Ist das zugrunde liegende Prinzip** wirklich so schwer zu verstehen?", "Неужели основной принцип так трудно понять?"),
        ])),

    P("ABS003", "ABS", "This reflects a wider trend toward… (общая тенденция)",
      "Связываем частное с общим: This reflects a wider trend toward… По-немецки: Dies spiegelt einen Trend zu … wider (widerspiegeln — отделяемый).",
      L("This reflects a wider trend toward …",
        "This reflects a wider trend toward remote work.",
        "Это отражает более общую тенденцию к удалённой работе.",
        [
            ("**This reflects a wider trend toward** remote work.", "Это отражает более общую тенденцию к удалённой работе."),
            ("**This reflects a wider trend toward** healthier eating.", "Это отражает более общую тенденцию к более здоровому питанию."),
            ("**This reflects a wider trend toward** digital payments.", "Это отражает более общую тенденцию к цифровым платежам."),
            ("**This reflects a wider trend toward** lifelong learning.", "Это отражает более общую тенденцию к обучению в течение всей жизни."),
            ("**This reflects a wider trend toward** smaller households.", "Это отражает более общую тенденцию к уменьшению домохозяйств."),
            ("**This reflects a wider trend toward** sustainable products.", "Это отражает более общую тенденцию к экологичным продуктам."),
            ("**This reflects a wider trend toward** shorter attention spans.", "Это отражает более общую тенденцию к сокращению концентрации внимания."),
            ("**This reflects a wider trend toward** personalized services.", "Это отражает более общую тенденцию к персонализированным услугам."),
            ("**This reflects a wider trend toward** urban living.", "Это отражает более общую тенденцию к городской жизни."),
            ("**This reflects a wider trend toward** greater transparency.", "Это отражает более общую тенденцию к большей прозрачности."),
            ("**This reflects a wider trend toward** flexible working hours.", "Это отражает более общую тенденцию к гибкому рабочему времени."),
            ("**Does this reflect a wider trend toward** automation?", "Отражает ли это более общую тенденцию к автоматизации?"),
        ]),
      L("Dies spiegelt einen allgemeineren Trend zu … wider",
        "Dies spiegelt einen allgemeineren Trend zur Heimarbeit wider.",
        "Это отражает более общую тенденцию к удалённой работе.",
        [
            ("**Dies spiegelt einen allgemeineren Trend** zur Heimarbeit **wider**.", "Это отражает более общую тенденцию к удалённой работе."),
            ("**Dies spiegelt einen allgemeineren Trend** zu gesünderer Ernährung **wider**.", "Это отражает более общую тенденцию к более здоровому питанию."),
            ("**Dies spiegelt einen allgemeineren Trend** zu digitalen Zahlungen **wider**.", "Это отражает более общую тенденцию к цифровым платежам."),
            ("**Dies spiegelt einen allgemeineren Trend** zum lebenslangen Lernen **wider**.", "Это отражает более общую тенденцию к обучению в течение всей жизни."),
            ("**Dies spiegelt einen allgemeineren Trend** zu kleineren Haushalten **wider**.", "Это отражает более общую тенденцию к уменьшению домохозяйств."),
            ("**Dies spiegelt einen allgemeineren Trend** zu nachhaltigen Produkten **wider**.", "Это отражает более общую тенденцию к экологичным продуктам."),
            ("**Dies spiegelt einen allgemeineren Trend** zu kürzeren Aufmerksamkeitsspannen **wider**.", "Это отражает более общую тенденцию к сокращению концентрации."),
            ("**Dies spiegelt einen allgemeineren Trend** zu personalisierten Diensten **wider**.", "Это отражает более общую тенденцию к персонализированным услугам."),
            ("**Dies spiegelt einen allgemeineren Trend** zum städtischen Leben **wider**.", "Это отражает более общую тенденцию к городской жизни."),
            ("**Dies spiegelt einen allgemeineren Trend** zu mehr Transparenz **wider**.", "Это отражает более общую тенденцию к большей прозрачности."),
            ("**Dies spiegelt einen allgemeineren Trend** zu flexiblen Arbeitszeiten **wider**.", "Это отражает более общую тенденцию к гибкому рабочему времени."),
            ("**Spiegelt dies einen allgemeineren Trend** zur Automatisierung **wider**?", "Отражает ли это более общую тенденцию к автоматизации?"),
        ])),

    # ============================================================ DATA — Numbers / data / trends
    P("DATA001", "DATA", "rise / grow from X to Y (описание данных)",
      "C1 описывает цифры точно: rise/increase/grow from X to Y. По-немецки: steigen/wachsen von X auf Y. Обратите внимание на предлог from…to / von…auf.",
      L("increase / rise / grow from X to Y",
        "Sales rose from 10 to 15 million in a year.",
        "Продажи выросли с 10 до 15 миллионов за год.",
        [
            ("Sales **rose from** 10 **to** 15 million in a year.", "Продажи выросли с 10 до 15 миллионов за год."),
            ("The price **increased from** $20 **to** $25.", "Цена выросла с 20 до 25 долларов."),
            ("Temperatures **climbed from** 15 **to** 28 degrees.", "Температура поднялась с 15 до 28 градусов."),
            ("The population **grew from** one **to** two million.", "Население выросло с одного до двух миллионов."),
            ("Unemployment **fell from** 8% **to** 5%.", "Безработица упала с 8% до 5%."),
            ("Profits **jumped from** 2 **to** 5 billion.", "Прибыль подскочила с 2 до 5 миллиардов."),
            ("The number of users **rose from** 100 **to** 500.", "Число пользователей выросло со 100 до 500."),
            ("Interest rates **increased from** 1% **to** 3%.", "Процентные ставки выросли с 1% до 3%."),
            ("Attendance **dropped from** 300 **to** 200 people.", "Посещаемость упала с 300 до 200 человек."),
            ("The budget **expanded from** 50 **to** 80 million.", "Бюджет вырос с 50 до 80 миллионов."),
            ("Traffic **increased from** 1,000 **to** 3,000 cars a day.", "Трафик вырос с 1000 до 3000 машин в день."),
            ("Did sales really **rise from** 10 **to** 15 million?", "Действительно ли продажи выросли с 10 до 15 миллионов?"),
        ]),
      L("steigen / wachsen von X auf Y",
        "Die Verkäufe stiegen von 10 auf 15 Millionen in einem Jahr.",
        "Продажи выросли с 10 до 15 миллионов за год.",
        [
            ("Die Verkäufe **stiegen von** 10 **auf** 15 Millionen in einem Jahr.", "Продажи выросли с 10 до 15 миллионов за год."),
            ("Der Preis **stieg von** 20 **auf** 25 Dollar.", "Цена выросла с 20 до 25 долларов."),
            ("Die Temperaturen **kletterten von** 15 **auf** 28 Grad.", "Температура поднялась с 15 до 28 градусов."),
            ("Die Bevölkerung **wuchs von** einer **auf** zwei Millionen.", "Население выросло с одного до двух миллионов."),
            ("Die Arbeitslosigkeit **sank von** 8% **auf** 5%.", "Безработица упала с 8% до 5%."),
            ("Die Gewinne **sprangen von** 2 **auf** 5 Milliarden.", "Прибыль подскочила с 2 до 5 миллиардов."),
            ("Die Zahl der Nutzer **stieg von** 100 **auf** 500.", "Число пользователей выросло со 100 до 500."),
            ("Die Zinsen **stiegen von** 1% **auf** 3%.", "Процентные ставки выросли с 1% до 3%."),
            ("Die Besucherzahlen **fielen von** 300 **auf** 200.", "Посещаемость упала с 300 до 200."),
            ("Das Budget **wuchs von** 50 **auf** 80 Millionen.", "Бюджет вырос с 50 до 80 миллионов."),
            ("Der Verkehr **stieg von** 1.000 **auf** 3.000 Autos pro Tag.", "Трафик вырос с 1000 до 3000 машин в день."),
            ("**Stiegen** die Verkäufe wirklich **von** 10 **auf** 15 Millionen?", "Действительно ли продажи выросли с 10 до 15 миллионов?"),
        ])),

    P("DATA002", "DATA", "remain relatively stable / decline slightly",
      "Не всё резко растёт или падает. C1 описывает слабую динамику: remain relatively stable, decline slightly. По-немецки: relativ stabil bleiben / leicht zurückgehen.",
      L("remain relatively stable / decline slightly",
        "Prices remained relatively stable throughout the year.",
        "Цены оставались относительно стабильными в течение года.",
        [
            ("Prices **remained relatively stable** throughout the year.", "Цены оставались относительно стабильными в течение года."),
            ("Sales **declined slightly** in the second quarter.", "Продажи немного снизились во втором квартале."),
            ("The unemployment rate **remained relatively stable**.", "Уровень безработицы оставался относительно стабильным."),
            ("Demand **fell slightly** after the holiday season.", "Спрос немного упал после праздников."),
            ("Temperatures **stayed relatively stable** overnight.", "Температура оставалась относительно стабильной ночью."),
            ("The number of visitors **declined slightly** this month.", "Число посетителей в этом месяце немного снизилось."),
            ("Support for the plan **remained relatively stable**.", "Поддержка плана оставалась относительно стабильной."),
            ("Profits **dipped slightly** but recovered quickly.", "Прибыль немного просела, но быстро восстановилась."),
            ("The exchange rate **remained relatively stable**.", "Обменный курс оставался относительно стабильным."),
            ("Costs **rose slightly** over the summer.", "Расходы за лето немного выросли."),
            ("Interest in the course **stayed relatively stable**.", "Интерес к курсу оставался относительно стабильным."),
            ("Did sales really **remain relatively stable**?", "Действительно ли продажи оставались относительно стабильными?"),
        ]),
      L("relativ stabil bleiben / leicht zurückgehen",
        "Die Preise blieben das ganze Jahr über relativ stabil.",
        "Цены оставались относительно стабильными в течение года.",
        [
            ("Die Preise **blieben** das ganze Jahr über **relativ stabil**.", "Цены оставались относительно стабильными в течение года."),
            ("Die Verkäufe **gingen** im zweiten Quartal **leicht zurück**.", "Продажи немного снизились во втором квартале."),
            ("Die Arbeitslosenquote **blieb relativ stabil**.", "Уровень безработицы оставался относительно стабильным."),
            ("Die Nachfrage **ging** nach den Feiertagen **leicht zurück**.", "Спрос немного упал после праздников."),
            ("Die Temperaturen **blieben** über Nacht **relativ stabil**.", "Температура оставалась относительно стабильной ночью."),
            ("Die Zahl der Besucher **ging** diesen Monat **leicht zurück**.", "Число посетителей в этом месяце немного снизилось."),
            ("Die Unterstützung für den Plan **blieb relativ stabil**.", "Поддержка плана оставалась относительно стабильной."),
            ("Die Gewinne **gingen leicht zurück**, erholten sich aber schnell.", "Прибыль немного просела, но быстро восстановилась."),
            ("Der Wechselkurs **blieb relativ stabil**.", "Обменный курс оставался относительно стабильным."),
            ("Die Kosten **stiegen** über den Sommer **leicht an**.", "Расходы за лето немного выросли."),
            ("Das Interesse am Kurs **blieb relativ stabil**.", "Интерес к курсу оставался относительно стабильным."),
            ("**Blieben** die Verkäufe wirklich **relativ stabil**?", "Действительно ли продажи оставались относительно стабильными?"),
        ])),

    P("DATA003", "DATA", "correlation does not imply causation",
      "Ключевой мыслительный C1-оборот: correlation does not (necessarily) imply causation — «корреляция не означает причинность». По-немецки: Korrelation bedeutet nicht zwangsläufig Kausalität.",
      L("correlation does not (necessarily) imply causation",
        "Correlation does not necessarily imply causation.",
        "Корреляция не обязательно означает причинность.",
        [
            ("**Correlation does not necessarily imply causation**.", "Корреляция не обязательно означает причинность."),
            ("We must remember that **correlation does not imply causation**.", "Мы должны помнить, что корреляция не означает причинность."),
            ("Just because two things correlate does not mean one causes the other.", "То, что две вещи коррелируют, не значит, что одна вызывает другую."),
            ("The study shows a correlation, but that **does not imply causation**.", "Исследование показывает корреляцию, но это не означает причинность."),
            ("**Correlation alone does not imply causation**.", "Одна лишь корреляция не означает причинность."),
            ("It's a classic mistake to assume that correlation implies causation.", "Классическая ошибка — считать, что корреляция означает причинность."),
            ("A strong correlation **does not necessarily imply** a causal link.", "Сильная корреляция не обязательно означает причинную связь."),
            ("Ice cream sales and drowning correlate, but that **does not imply causation**.", "Продажи мороженого и утопления коррелируют, но это не означает причинность."),
            ("**Correlation does not imply causation**; a third factor may be at play.", "Корреляция не означает причинность; может действовать третий фактор."),
            ("We found a correlation, yet we cannot imply causation.", "Мы нашли корреляцию, но не можем утверждать причинность."),
            ("The correlation is striking, but **correlation does not imply causation**.", "Корреляция поразительна, но корреляция не означает причинность."),
            ("Does correlation really imply causation in this case?", "Действительно ли корреляция означает причинность в этом случае?"),
        ]),
      L("Korrelation bedeutet nicht zwangsläufig Kausalität",
        "Korrelation bedeutet nicht zwangsläufig Kausalität.",
        "Корреляция не обязательно означает причинность.",
        [
            ("**Korrelation bedeutet nicht zwangsläufig Kausalität**.", "Корреляция не обязательно означает причинность."),
            ("Wir müssen bedenken, dass Korrelation keine Kausalität bedeutet.", "Мы должны помнить, что корреляция не означает причинность."),
            ("Nur weil zwei Dinge korrelieren, bedeutet das nicht, dass eines das andere verursacht.", "То, что две вещи коррелируют, не значит, что одна вызывает другую."),
            ("Die Studie zeigt eine Korrelation, aber das **bedeutet keine Kausalität**.", "Исследование показывает корреляцию, но это не означает причинность."),
            ("**Korrelation allein bedeutet keine Kausalität**.", "Одна лишь корреляция не означает причинность."),
            ("Es ist ein klassischer Fehler anzunehmen, dass Korrelation Kausalität bedeutet.", "Классическая ошибка — считать, что корреляция означает причинность."),
            ("Eine starke Korrelation **bedeutet nicht zwangsläufig** einen ursächlichen Zusammenhang.", "Сильная корреляция не обязательно означает причинную связь."),
            ("Eisverkauf und Ertrinken korrelieren, aber das **bedeutet keine Kausalität**.", "Продажи мороженого и утопления коррелируют, но это не означает причинность."),
            ("**Korrelation bedeutet keine Kausalität**; ein dritter Faktor kann eine Rolle spielen.", "Корреляция не означает причинность; может действовать третий фактор."),
            ("Wir fanden eine Korrelation, können aber keine Kausalität behaupten.", "Мы нашли корреляцию, но не можем утверждать причинность."),
            ("Die Korrelation ist auffällig, aber **Korrelation bedeutet keine Kausalität**.", "Корреляция поразительна, но корреляция не означает причинность."),
            ("Bedeutet Korrelation in diesem Fall wirklich Kausalität?", "Действительно ли корреляция означает причинность в этом случае?"),
        ])),
]


def main():
    data = json.load(open(SRC, encoding="utf-8"))
    existing = {p["id"].lower() for p in data}
    added = 0
    for rec in NEW:
        if rec["id"].lower() in existing:
            raise SystemExit(f"Duplicate id would be introduced: {rec['id']}")
        data.append(rec)
        existing.add(rec["id"].lower())
        added += 1
    with open(SRC, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"Added {added} new patterns. Total now: {len(data)}")


if __name__ == "__main__":
    main()
