from __future__ import annotations, unicode_literals
import spacy

irregular_verbs = {
    "be": "was/were  — been",
    "beat": "beat  — beaten",
    "become": "became  — become",
    "begin": "began  — begun",
    "bend": "bent  — bent",
    "bet": "bet  — bet",
    "bid": "bid  — bid",
    "bite": "bit  — bitten",
    "blow": "blew  — blown",
    "break": "broke  — broken",
    "bring": "brought  — brought",
    "build": "built  — built",
    "buy": "bought  — bought",
    "catch": "caught  — caught",
    "choose": "chose  — chosen",
    "come": "came  — come",
    "cost": "cost  — cost",
    "cut": "cut  — cut",
    "deal": "dealt  — dealt",
    "dig": "dug  — dug",
    "do": "did  — done",
    "draw": "drew  — drawn",
    "drink": "drank  — drunk",
    "drive": "drove  — driven",
    "eat": "ate  — eaten",
    "fall": "fell  — fallen",
    "feed": "fed  — fed",
    "feel": "felt  — felt",
    "fight": "fought  — fought",
    "find": "found  — found",
    "fly": "flew  — flown",
    "forget": "forgot  — forgotten",
    "forgive": "forgave  — forgiven",
    "freeze": "froze  — frozen",
    "get": "got  — gotten",
    "give": "gave  — given",
    "go": "went  — gone",
    "grow": "grew  — grown",
    "hang": "hung  — hung",
    "have": "had  — had",
    "hear": "heard  — heard",
    "hide": "hid  — hidden",
    "hit": "hit  — hit",
    "hold": "held  — held",
    "hurt": "hurt  — hurt",
    "keep": "kept  — kept",
    "know": "knew  — known",
    "lay": "laid  — laid",
    "lead": "led  — led",
    "leave": "left  — left",
    "lend": "lent  — lent",
    "let": "let  — let",
    "lie": "lay  — lain",
    "light": "lit  — lit",
    "lose": "lost  — lost",
    "make": "made  — made",
    "mean": "meant  — meant",
    "meet": "met  — met",
    "pay": "paid  — paid",
    "put": "put  — put",
    "read": "read  — read",
    "ride": "rode  — ridden",
    "ring": "rang  — rung",
    "rise": "rose  — risen",
    "run": "ran  — run",
    "say": "said  — said",
    "see": "saw  — seen",
    "sell": "sold  — sold",
    "send": "sent  — sent",
    "set": "set  — set",
    "shake": "shook  — shaken",
    "shine": "shone  — shone",
    "shoot": "shot  — shot",
    "show": "showed  — shown",
    "shut": "shut  — shut",
    "sing": "sang  — sung",
    "sink": "sank  — sunk",
    "sit": "sat  — sat",
    "sleep": "slept  — slept",
    "slide": "slid  — slid",
    "speak": "spoke  — spoken",
    "spend": "spent  — spent",
    "spin": "spun  — spun",
    "split": "split  — split",
    "spread": "spread  — spread",
    "stand": "stood  — stood",
    "steal": "stole  — stolen",
    "stick": "stuck  — stuck",
    "strike": "struck  — struck",
    "swear": "swore  — sworn",
    "sweep": "swept  — swept",
    "swim": "swam  — swum",
    "take": "took  — taken",
    "teach": "taught  — taught",
    "tear": "tore  — torn",
    "tell": "told  — told",
    "think": "thought  — thought",
    "throw": "threw  — thrown",
    "understand": "understood  — understood",
    "wake": "woke  — woken",
    "wear": "wore  — worn",
    "win": "won  — won",
    "write": "wrote  — written",
    "buy": "bought  — bought",
    "draw": "drew  — drawn",
    "dream": "dreamt  — dreamt",
    "drink": "drank  — drunk",
    "drive": "drove  — driven",
    "eat": "ate  — eaten",
    "fall": "fell  — fallen",
    "feel": "felt  — felt",
    "find": "found  — found",
    "fly": "flew  — flown",
    "forget": "forgot  — forgotten",
    "get": "got  — got",
    "give": "gave  — given",
    "go": "went  — gone",
    "grow": "grew  — grown",
    "hang": "hung  — hung",
    "have": "had  — had",
    "hear": "heard  — heard",
    "hide": "hid  — hidden",
    "hit": "hit  — hit",
    "hold": "held  — held",
    "hurt": "hurt  — hurt",
    "keep": "kept  — kept",
    "know": "knew  — known",
    "learn": "learnt  — learnt",
    "leave": "left  — left",
    "lend": "lent  — lent",
    "let": "let  — let",
    "lose": "lost  — lost",
    "make": "made  — made",
    "mean": "meant  — meant",
    "meet": "met  — met",
    "pay": "paid  — paid",
    "put": "put  — put",
    "read": "read  — read",
    "ride": "rode  — ridden",
    "ring": "rang  — rung",
    "rise": "rose  — risen",
    "run": "ran  — run",
    "say": "said  — said",
    "see": "saw  — seen",
    "sell": "sold  — sold",
    "send": "sent  — sent",
    "set": "set  — set",
    "sew": "sewed  — sewn",
    "shake": "shook  — shaken",
    "shine": "shone  — shone",
    "shoot": "shot  — shot",
    "show": "showed  — shown",
    "shrink": "shrank  — shrunk",
    "sing": "sang  — sung",
    "sink": "sank  — sunk",
    "sit": "sat  — sat",
    "sleep": "slept  — slept",
    "slide": "slid  — slid",
    "speak": "spoke  — spoken",
    "spend": "spent  — spent",
    "spread": "spread  — spread",
    "stand": "stood  — stood",
    "steal": "stole  — stolen",
    "stick": "stuck  — stuck",
    "swim": "swam  — swum",
    "take": "took  — taken",
    "teach": "taught  — taught",
    "tear": "tore  — torn",
    "tell": "told  — told",
    "think": "thought  — thought",
    "throw": "threw  — thrown",
    "understand": "understood  — understood",
    "wake": "woke  — woken",
    "wear": "wore  — worn",
    "win": "won  — won",
    "write": "wrote  — written",
    "awake": "awoke  — awoken",
    "bear": "bore  — borne",
    "beat": "beat  — beaten",
    "become": "became  — become",
    "begin": "began  — begun",
    "bend": "bent  — bent",
    "bet": "bet  — bet",
    "bid": "bid  — bid/bidden",
    "bite": "bit  — bitten",
    "bleed": "bled  — bled",
    "blow": "blew  — blown",
    "break": "broke  — broken",
    "bring": "brought  — brought",
    "build": "built  — built",
    "burn": "burnt  — burnt",
    "burst": "burst  — burst",
    "buy": "bought  — bought",
    "cast": "cast  — cast",
    "catch": "caught  — caught",
    "choose": "chose  — chosen",
    "cling": "clung  — clung",
    "come": "came  — come",
    "cost": "cost  — cost",
    "creep": "crept  — crept",
    "cut": "cut  — cut",
    "deal": "dealt  — dealt",
    "dig": "dug  — dug",
    "dive": "dived  — dived",
    "do": "did  — done",
    "draw": "drew  — drawn",
    "dream": "dreamt  — dreamt",
    "drink": "drank  — drunk",
    "drive": "drove  — driven",
    "eat": "ate  — eaten",
    "fall": "fell  — fallen",
    "feed": "fed  — fed",
    "feel": "felt  — felt",
    "fight": "fought  — fought",
    "find": "found  — found",
    "fit": "fit  — fit",
    "flee": "fled  — fled",
    "fling": "flung  — flung",
    "fly": "flew  — flown",
    "forbid": "forbade  — forbidden",
    "forget": "forgot  — forgotten",
    "forgive": "forgave  — forgiven",
    "forsake": "forsook  — forsaken",
    "freeze": "froze  — frozen",
    "get": "got  — gotten",
    "give": "gave  — given",
    "go": "went  — gone",
    "grind": "ground  — ground",
    "grow": "grew  — grown",
    "hang": "hung  — hung",
    "have": "had  — had",
    "hear": "heard  — heard",
    "hide": "hid  — hidden",
    "hit": "hit  — hit",
    "hold": "held  — held",
    "hurt": "hurt  — hurt",
    "keep": "kept  — kept",
    "kneel": "knelt  — knelt",
    "knit": "knit  — knit",
    "know": "knew  — known",
    "lay": "laid  — laid",
    "lead": "led  — led",
    "lean": "leant  — leant",
    "leap": "leapt  — leapt",
    "learn": "learnt  — learnt",
    "leave": "left  — left",
    "lend": "lent  — lent",
    "let": "let  — let",
    "lie": "lay  — lain",
    "light": "lit  — lit",
    "lose": "lost  — lost",
    "make": "made  — made",
    "mean": "meant  — meant",
    "meet": "met  — met",
    "mow": "mowed  — mown",
    "pay": "paid  — paid",
    "put": "put  — put",
    "read": "read  — read",
    "ride": "rode  — ridden",
    "ring": "rang  — rung",
    "rise": "rose  — risen",
    "run": "ran  — run",
    "saw": "sawed  — sawn",
    "say": "said  — said",
    "see": "saw  — seen",
    "seek": "sought  — sought",
    "sell": "sold  — sold",
    "send": "sent  — sent",
    "set": "set  — set",
    "sew": "sewed  — sewn",
    "shake": "shook  — shaken",
    "shine": "shone  — shone",
    "shoot": "shot  — shot",
    "show": "showed  — shown",
    "shrink": "shrank  — shrunk",
    "shut": "shut  — shut",
    "sing": "sang  — sung",
    "sink": "sank  — sunk",
    "sit": "sat  — sat",
    "sleep": "slept  — slept",
    "slide": "slid  — slid",
    "sling": "slung  — slung",
    "slit": "slit  — slit",
    "smite": "smote  — smitten",
    "sow": "sowed  — sown",
    "speak": "spoke  — spoken",
    "speed": "sped  — sped",
    "spend": "spent  — spent",
    "spin": "spun  — spun",
    "spit": "spat  — spat",
    "split": "split  — split",
    "spoil": "spoilt  — spoilt",
    "spread": "spread  — spread",
    "spring": "sprang  — sprung",
    "stand": "stood  — stood",
    "steal": "stole  — stolen",
    "stick": "stuck  — stuck",
    "sting": "stung  — stung",
    "stink": "stank  — stunk",
    "stride": "strode  — stridden",
    "strike": "struck  — struck",
    "strive": "strove  — striven",
    "swear": "swore  — sworn",
    "sweep": "swept  — swept",
    "swell": "swelled  — swollen",
    "swim": "swam  — swum",
    "swing": "swung  — swung",
    "take": "took  — taken",
    "teach": "taught  — taught",
    "tear": "tore  — torn",
    "tell": "told  — told",
    "think": "thought  — thought",
    "thrive": "throve  — thriven",
    "throw": "threw  — thrown",
    "thrust": "thrust  — thrust",
    "tread": "trod  — trodden",
    "understand": "understood  — understood",
    "wake": "woke  — woken",
    "wear": "wore  — worn",
    "weave": "wove  — woven",
    "wed": "wed  — wed",
    "weep": "wept  — wept",
    "win": "won  — won",
    "wind": "wound  — wound",
    "wring": "wrung  — wrung",
    "write": "wrote  — written",
}


class enChunks:
    def __init__(self, document: spacy.tokens.doc.Doc):
        self.document = document
        self.chunks = []

        self.irregular_verbs = irregular_verbs
        self.process()

    def process(self):

        for token in self.document:

            if token.lemma_ in self.irregular_verbs.keys() and token.pos_ == "VERB":
                verb_forms = self.irregular_verbs[token.lemma_]
                self.chunks.append(f"{token.lemma_.lower()} — {verb_forms}")

            # there + be
            if token.dep_ == "expl" and token.text.lower() == "there":
                if self.document.noun_chunks:
                    self.chunks.append(
                        f"{token.text} {token.head.text} {next(iter(self.document.noun_chunks)).text}"
                    )

            if (
                token.pos_ == "ADP"
                and token.text.lower() == "as"
                and token.i + 4 < len(self.document)
            ):
                article = self.document[token.i + 1]
                noun = self.document[token.i + 2]
                preposition = self.document[token.i + 3]

                if (
                    article.pos_ == "DET"
                    and noun.pos_ == "NOUN"
                    and preposition.pos_ == "ADP"
                ):
                    self.chunks.append(
                        f"{token.text} {article.text} {noun.text} {preposition.text}"
                    )
        # 4) Noun chunks
        for chunk in self.document.noun_chunks:
            if (
                len(chunk) > 2
                and not chunk.text[0].lower().startswith("'")
                and not chunk.text[0].lower().startswith('"')
            ):
                self.chunks.append(chunk.text[0].lower() + chunk.text[1:])

    def get(self):
        chunkListFinal = "^".join(self.chunks)
        return chunkListFinal
